{
  config,
  inputs,
  lib,
  pkgs,
  system,
  ...
}:
let
  stateDir = "${config.flags.externalStoragePath}/.openclaw";
  cacheDir = "${config.flags.externalStoragePath}/.cache";
  # Installed by local.tools.npm.packages in tools.nix
  openclawBin = "${config.flags.externalStoragePath}/.npm/bin/openclaw";
  gatewayPort = 18789;

  # TODO: mlx-whisper needs MLX >= 0.31 for stable GPU inference.
  # Falls back to OpenAI until nixpkgs bumps MLX.
  # https://github.com/NixOS/nixpkgs/pull/504828
  mlxWhisperWrapper = pkgs.writeShellScript "mlx-whisper-openclaw" ''
    export HF_HOME="${cacheDir}/huggingface"
    exec ${pkgs.mlx-whisper}/bin/mlx_whisper \
      --model mlx-community/whisper-turbo \
      --output_dir ${config.flags.externalStoragePath}/Tmp \
      "$@"
  '';
  patchedConfig = "${stateDir}/openclaw-runtime.json";

  # JSON config generated by nix — same structure as nix-openclaw produced,
  # but without requiring the nix-openclaw flake input at all.
  openclawConfig = pkgs.writeText "openclaw.json" (
    builtins.toJSON {
      agents.defaults = {
        workspace = "${stateDir}/workspace";

        model = {
          primary = "anthropic/claude-opus-4-6";
        };

        models = {
          "anthropic/claude-opus-4-6" = {
            alias = "opus";
          };
        };
      };

      gateway = {
        mode = "local";
        port = gatewayPort;
        auth.mode = "token";
        # FIXME: Reverse proxy pairing workaround. Remove when upstream fixes land.
        # https://github.com/openclaw/openclaw/issues/1679
        # https://github.com/openclaw/openclaw/issues/49293
        trustedProxies = [
          "127.0.0.1"
          "::1"
        ];
        controlUi.allowInsecureAuth = true;
      };

      channels.discord = {
        enabled = true;
        execApprovals = {
          enabled = true;
          target = "channel";
        };
      };

      approvals.exec = {
        enabled = true;
        mode = "session";
        sessionFilter = [ "discord" ];
      };

      tools.exec = {
        security = "full";
        ask = "off";
      };

      tools.media.audio = {
        enabled = true;
        echoTranscript = true;
        models = [
          {
            type = "cli";
            command = "${pkgs.openai-whisper}/bin/whisper";
            args = [
              "--model"
              "turbo"
              "--model_dir"
              "${cacheDir}/whisper"
              "--output_dir"
              "${config.flags.externalStoragePath}/Tmp"
              "{{MediaPath}}"
            ];
            timeoutSeconds = 300;
          }
          {
            type = "cli";
            command = "${mlxWhisperWrapper}";
            args = [ "{{MediaPath}}" ];
            timeoutSeconds = 300;
          }
          {
            provider = "openai";
            model = "gpt-4o-mini-transcribe";
          }
        ];
      };

      session.reset = {
        mode = "daily";
        atHour = 4;
      };

      tools.web.search = {
        provider = "gemini";
      };

      skills.load.extraDirs = [
        "${config.flags.externalStoragePath}/Sources/github.com/openclaw/openclaw/skills"
      ];

      # Disable slack — we only use discord and the bundled slack extension
      # is missing @slack/web-api at runtime.
      plugins.entries.slack.enabled = false;

    }
  );

  # Wrapper that patches config with SecretRefs and dynamic values, then execs the gateway.
  # Secrets are injected as file-based SecretRefs so they stay out of process.env
  # and are not visible to agents via `env`.
  gatewayWithSecrets = pkgs.writeShellScript "openclaw-gateway-secrets" ''
    DOMAIN=$(cat ${config.sops.secrets.external-domain.path})
    SERVER_ID=$(cat ${config.sops.secrets.openclaw-discord-server-id.path})
    USER_ID=$(cat ${config.sops.secrets.openclaw-discord-user-id.path})
    ${pkgs.jq}/bin/jq \
      --arg origin "https://openclaw.$DOMAIN" \
      --arg serverId "$SERVER_ID" \
      --arg userId "$USER_ID" \
      --arg gatewayTokenPath "${config.sops.secrets.openclaw-gateway-token.path}" \
      --arg discordTokenPath "${config.sops.secrets.openclaw-discord-bot-token.path}" \
      --arg anthropicTokenPath "${config.sops.secrets.openclaw-claude-oauth-token.path}" \
      --arg geminiApiKeyPath "${config.sops.secrets.openclaw-gemini-api-key.path}" \
      --arg perplexityApiKeyPath "${config.sops.secrets.openclaw-perplexity-api-key.path}" \
      \
      '
       .secrets.providers["sops-gateway-token"] = { source: "file", path: $gatewayTokenPath, mode: "singleValue" }
       | .secrets.providers["sops-discord-token"] = { source: "file", path: $discordTokenPath, mode: "singleValue" }
       | .secrets.providers["sops-anthropic-token"] = { source: "file", path: $anthropicTokenPath, mode: "singleValue" }
       | .secrets.providers["sops-gemini-api-key"] = { source: "file", path: $geminiApiKeyPath, mode: "singleValue" }
       | .secrets.providers["sops-perplexity-api-key"] = { source: "file", path: $perplexityApiKeyPath, mode: "singleValue" }

       | .gateway.auth.token = { source: "file", provider: "sops-gateway-token", id: "value" }
       | .channels.discord.token = { source: "file", provider: "sops-discord-token", id: "value" }
       | .models.providers.anthropic = {
           baseUrl: "https://api.anthropic.com",
           models: [],
           apiKey: { source: "file", provider: "sops-anthropic-token", id: "value" }
         }

       | .plugins.entries.google.enabled = true
       | .plugins.entries.google.config.webSearch.apiKey = { source: "file", provider: "sops-gemini-api-key", id: "value" }
       | .plugins.entries.perplexity.enabled = true
       | .plugins.entries.perplexity.config.webSearch.apiKey = { source: "file", provider: "sops-perplexity-api-key", id: "value" }
       | .gateway.controlUi.allowedOrigins = [$origin, "http://127.0.0.1:${toString gatewayPort}"]
       | .channels.discord.allowFrom = [$userId]
       | .channels.discord.guilds[$serverId] = {}
       | .channels.discord.execApprovals.approvers = [$userId]
       ' "${openclawConfig}" > "${patchedConfig}.tmp"
    mv "${patchedConfig}.tmp" "${patchedConfig}"
    export OPENCLAW_CONFIG_PATH="${patchedConfig}"

    exec ${openclawBin} gateway --port ${toString gatewayPort}
  '';

  steipeteTools = inputs.nix-steipete-tools.packages.${system};

  toolsPath = lib.makeBinPath [
    pkgs.nodejs_22
    pkgs.git
    pkgs.jq
    pkgs.ripgrep
    pkgs.curl
    pkgs.ffmpeg
    pkgs.sox
    pkgs.python3
    pkgs.openai-whisper
    steipeteTools.summarize
    steipeteTools.peekaboo
    steipeteTools.sag
  ];
in
{
  # Gateway service via home-manager launchd module
  local.launchd.services.openclaw-gateway = {
    enable = true;
    waitForPath = config.flags.externalStoragePath;
    waitForSecrets = true;
    dataDir = stateDir;
    extraDirs = [
      "${stateDir}/logs"
      "${stateDir}/workspace"
    ];
    command = "${gatewayWithSecrets}";
    environment = {
      OPENCLAW_CONFIG_PATH = patchedConfig;
      OPENCLAW_STATE_DIR = stateDir;
      PATH = "${toolsPath}:/usr/bin:/bin";
    };
  };

  # Point CLI at the same state/config the gateway uses on external storage
  home.sessionVariables = {
    OPENCLAW_STATE_DIR = stateDir;
    OPENCLAW_CONFIG_PATH = patchedConfig;
  };

  # Seed exec-approvals.json with full-access defaults (YOLO mode).
  # Migrate existing installs from allowlist to full.
  home.activation.openclawExecApprovals = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        EA="${stateDir}/exec-approvals.json"
        if [ ! -f "$EA" ]; then
          cat > "$EA" <<'EAJSON'
    {
      "version": 1,
      "defaults": {
        "security": "full",
        "ask": "off",
        "askFallback": "full",
        "autoAllowSkills": true
      },
      "agents": {}
    }
    EAJSON
          chmod 600 "$EA"
        else
          ${pkgs.jq}/bin/jq '.defaults = {
            security: "full",
            ask: "off",
            askFallback: "full",
            autoAllowSkills: true
          }' "$EA" > "$EA.tmp" && mv "$EA.tmp" "$EA"
        fi
  '';

  # Restart gateway when config content changes (nix store path of
  # openclawConfig changes on any config edit, so the hash changes).
  home.activation.openclawGatewayRestart = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    CONFIG_HASH_SOURCE="${openclawConfig}"
    HASH_FILE="${stateDir}/.config-hash"

    CURRENT_HASH=$(/usr/bin/shasum -a 256 "$CONFIG_HASH_SOURCE" 2>/dev/null | /usr/bin/cut -d' ' -f1 || echo "")
    STORED_HASH=$(/bin/cat "$HASH_FILE" 2>/dev/null || echo "")

    if [ "$CURRENT_HASH" != "$STORED_HASH" ]; then
      echo "$CURRENT_HASH" > "$HASH_FILE"
      # Only restart if hash file already existed (skip on first activation
      # since the gateway will start fresh via RunAtLoad anyway).
      if [ -n "$STORED_HASH" ]; then
        /bin/launchctl kickstart -k "gui/$UID/com.steipete.openclaw.gateway" 2>/dev/null || true
      fi
    fi
  '';

  home.activation.openclawDashboardUrl = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    MARKER="${stateDir}/.dashboard-url-shown"
    if [ ! -f "$MARKER" ]; then
      TOKEN=$(cat ${config.sops.secrets.openclaw-gateway-token.path} 2>/dev/null || echo "")
      if [ -n "$TOKEN" ]; then
        DOMAIN=$(cat ${config.sops.secrets.external-domain.path} 2>/dev/null || echo "")
        if [ -n "$DOMAIN" ]; then
          /usr/bin/sudo -u ivan /usr/bin/open "https://openclaw.$DOMAIN/#token=$TOKEN"
          touch "$MARKER"
        fi
      fi
    fi
  '';

  sops.secrets.openclaw-discord-bot-token = {
    key = "discord/LizardBotToken";
  };

  sops.secrets.openclaw-claude-oauth-token = {
    key = "anthropic/oauthTokenOpenClaw";
  };

  sops.secrets.openclaw-gateway-token = {
    key = "openClaw/gatewayToken";
  };

  sops.secrets.openclaw-discord-server-id = {
    key = "discord/serverId";
  };

  sops.secrets.openclaw-discord-user-id = {
    key = "discord/userId";
  };

  sops.secrets.openclaw-discord-channel-id = {
    key = "discord/openClawChannelId";
  };

  sops.secrets.openclaw-gemini-api-key = {
    key = "geminiApiKey";
  };

  sops.secrets.openclaw-perplexity-api-key = {
    key = "perplexityApiToken";
  };
}
