{
  inputs,
  pkgs,
  system,
  ...
}:
let
  steipeteTools = inputs.nix-steipete-tools.packages.${system};
in
{
  home.packages =
    (with pkgs; [
      (python313.withPackages (
        ps: with ps; [
          grip
          markitdown
        ]
      ))
      git-restore
      abs
      abs-mgmt
      age
      ai
      aria2
      arr-mgmt
      asusrouter-cli
      audio-extract
      backup-home
      bat
      bbw
      beszel-mgmt
      btop
      cargo
      claude-statusline
      cleanup-home
      delta
      diff-deep
      diff-long-lines
      discordo
      dns
      duf
      dust
      eat
      erdtree
      exiftool
      ffmpeg
      find-grep
      firefox-selecttab
      forgejo-mgmt
      fzf
      gallery-dl
      genpass
      gh-notifications
      gh-pr
      gh-stars-migrate
      giffer
      gitleaks
      git-branch
      git-commit-scope
      git-pull-all
      git-repo-dl
      git-root-root
      git-switch
      go-grip
      go-lint-wrapper
      gofumpt
      golangci-lint
      gpg-edit
      gpg-pass-refresh
      gwq
      grwt
      gwq-add
      gwq-merge
      gwq-purge
      healthchecks-mgmt
      home-manager
      image-meta
      imagemagick
      jellyfin-mgmt
      jq
      jpg-converter
      launchd-mgmt
      macmon
      magic-wormhole
      mkcd
      mkpasswd
      music-export
      nextdns-mgmt
      nix-gc
      nix-generate-sha
      nix-sort-imports
      nixfmt-rfc-style
      nixpkgs-darwin-master-ytdlp.yt-dlp
      nodePackages.prettier
      nodejs
      notes
      nvim-edit-staged
      obs
      open-pr
      pandoc
      parallel
      pass-fzf
      paste-loop
      path-copy
      perlite
      perplexity
      pigz
      poppler-utils
      poweroff
      ps-top
      ps-top-nu
      pv
      rbwget
      rclone
      reboot
      rebuild
      rems
      reposync
      rg-all
      rg-find
      ripgrep
      ruff
      rust-analyzer
      rustc
      sesh
      settings
      shellcheck
      shfmt
      smctemp # Local overlay
      sops
      ssh-persistent
      ssh-to-age
      statix-wrapper
      stylua
      swiftformat
      syncthing
      syncthing-mgmt
      tac
      tail-terminal
      task-new
      taskmanager
      tmux-attach
      tmux-spawn
      top-top
      torrent-dl
      torrent-watcher
      tree
      treefmt
      typst
      typstyle
      uptime-kuma-mgmt
      username # Installed as flake
      watcher
      watchman
      watchman-make
      wget
      yank
      yt-dlp-parallel
      zellij-session
      zsh-forgit
      ghq-cd
    ])
    ++ (with steipeteTools; [
      peekaboo
      sag
      summarize
    ]);
}
