{
  imports = [
    ../../../darwin/aerospace.nix
    ../../../darwin/darwin.nix
    ../../../darwin/rebuild-terminal.nix
    ../../../darwin/nix.nix
    ../../../darwin/no-dock-restart.nix
    ../../../darwin/sudo.nix
    ../../../darwin/syncthing.nix
    ../../../darwin/system.nix
    ../../../darwin/users.nix
    ../../../modules/darwin/dock
    ../../../modules/darwin/launchd
    ../../../modules/darwin/pam
    ../../../modules/darwin/pmset
    ../../../modules/darwin/prevent-sleep
    ../../../modules/darwin/rebuild-terminal
    ../../../modules/darwin/sudo
    ../../../modules/darwin/syncthing-mgmt
    ../../../modules/flags
    ../../../system/documentation.nix
    ../../../system/nix.nix
    ../../../system/scripts
    ./dns.nix
    ./dock.nix
    ./flags.nix
    ./fonts.nix
    ./git.nix
    ./homebrew.nix
    ./openssh.nix
    ./power.nix
    ./prevent-sleep.nix
    ./security.nix
    ./shell.nix
    ./sudo.nix
    ./syncthing-mgmt.nix
    ./users.nix
    ./close-zscaler.nix

    ../../../darwin/amethyst.nix
    ../../../darwin/hammerspoon.nix
    ../../../darwin/mos.nix
    ../../../darwin/stats.nix
    ../../../darwin/twingate.nix
  ];
}
