keys:
  - &home 6BD3724830BD941E9180C1A33A33FA4C82ED674F
  - &mini age1nxsvvlxhutf7kr26ucc60r48lge779dducnknyr9pceej52nqgnqlvqe25
  - &mini-user age12fac36qxkpulhakkz2e7z8efurgn3xzqv04ceuv4vjdcfnwcl3cs3cm7h9
  - &bee age1sxcheqlg4ztsu6ly3mfzmx7a2s7ht4znkez7q0g2rcmwr92tjfqqf29plr
  - &bee-user age13gw88tu64vjr0gmy442yaf7c6zd3ph96epqktr8ka4v5zea494mq9whmjw
  - &lusha age1d8zecgxstqurz80ecn0x55neucxss7dgpm63pkspzae7wtud5qtse0xcqy
  - &lusha-user age1rgdpf0u4mfpe74xwecknex6u3lcdpxm8jfydu4n8ftk4yjsngpdqp5rqa2
  - &macbook-pro-user age1x42q97xw3synk305twvsxkslld2205h97t8d9z8hy8vl8hzcpgas6d48rh

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
    - pgp:
      - *home
      age:
      - *mini
      - *mini-user
      - *bee
      - *bee-user
      - *lusha
      - *lusha-user
      - *macbook-pro-user
