keys:
  - &home 6BD3724830BD941E9180C1A33A33FA4C82ED674F
  - &a3 age1ya8kjpr8klstrfaq5xdu43t3lafe8wq2up3uhezhg9z3xaxc2ayssvsa59
  - &a3-user age1rw5u356cck5mx4ee5hjtqlc2380ycyvctddl6l3kwfj2nkqksf4qclnx0w
  - &mini age1t3hxyftxh0mqtj7j9nh9h4ph6g5j00frsvqvptjh8emtv9my8qcqx982ka
  - &mini-user age1s7wndc459u3azqegj66wcj5y9yydymnpwt7vzazsxagv3sjcwsfs2enwdu
  - &bee age1sxcheqlg4ztsu6ly3mfzmx7a2s7ht4znkez7q0g2rcmwr92tjfqqf29plr
  - &bee-user age13gw88tu64vjr0gmy442yaf7c6zd3ph96epqktr8ka4v5zea494mq9whmjw
  - &lusha age1d8zecgxstqurz80ecn0x55neucxss7dgpm63pkspzae7wtud5qtse0xcqy
  - &lusha-user age1rgdpf0u4mfpe74xwecknex6u3lcdpxm8jfydu4n8ftk4yjsngpdqp5rqa2
  - &macbook-pro age1grre437d8vhr7wlq2h05mtn8ufxddwdktzv6aw60qyuqgy87t4ps0f2tgs
  - &macbook-pro-user age1x42q97xw3synk305twvsxkslld2205h97t8d9z8hy8vl8hzcpgas6d48rh
  - &macbook-air age13sfhwx56gvfzprjzg2guzf5l27jsk5szu2n54tfc80q7s84w8etsfw550z
  - &macbook-air-user age13qs0kqn9gnyuv30xehzls8cvshs372j0g02lthfvn36s53erp4tsy2n854

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
    - pgp:
      - *home
      age:
      - *a3
      - *a3-user
      - *mini
      - *mini-user
      - *bee
      - *bee-user
      - *lusha
      - *lusha-user
      - *macbook-pro
      - *macbook-pro-user
      - *macbook-air
      - *macbook-air-user
