keys:
  - &home 6BD3724830BD941E9180C1A33A33FA4C82ED674F
  - &a3 age1ya8kjpr8klstrfaq5xdu43t3lafe8wq2up3uhezhg9z3xaxc2ayssvsa59
  - &a3-user age1rw5u356cck5mx4ee5hjtqlc2380ycyvctddl6l3kwfj2nkqksf4qclnx0w
  - &mini age1nxsvvlxhutf7kr26ucc60r48lge779dducnknyr9pceej52nqgnqlvqe25
  - &mini-user age12fac36qxkpulhakkz2e7z8efurgn3xzqv04ceuv4vjdcfnwcl3cs3cm7h9
  - &bee age1sxcheqlg4ztsu6ly3mfzmx7a2s7ht4znkez7q0g2rcmwr92tjfqqf29plr
  - &bee-user age13gw88tu64vjr0gmy442yaf7c6zd3ph96epqktr8ka4v5zea494mq9whmjw
  - &lusha age1d8zecgxstqurz80ecn0x55neucxss7dgpm63pkspzae7wtud5qtse0xcqy
  - &lusha-user age1rgdpf0u4mfpe74xwecknex6u3lcdpxm8jfydu4n8ftk4yjsngpdqp5rqa2
  - &macbook-pro-user age1x42q97xw3synk305twvsxkslld2205h97t8d9z8hy8vl8hzcpgas6d48rh
  - &steamdeck age1elhe3mnpf6fh5rcquljslu4j8rh0mk5wxraftf8gumgd47m9r5kq2wk2gx
  - &steamdeck-user age170z7hk7s4xyzq2s8s5dmhduusgpmpvhgfnjtuqhxkn76gg4pnayqzsrz7h

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
    - pgp:
      - *home
      age:
      - *a3
      - *a3-user
      - *mini
      - *mini-user
      - *bee
      - *bee-user
      - *lusha
      - *lusha-user
      - *macbook-pro-user
      - *steamdeck
      - *steamdeck-user
