name: <%= `hostname`.strip %>-nixos-config
startup_window: 0
root: <%= Dir.pwd %>

windows:
  - claude:
      layout: main-vertical
      panes:
        - claude
  - shell:
      layout: main-vertical
      panes:
        - ls -lah
  - nixos-config:
      layout: main-vertical
      panes:
        - nvim
