{
  config,
  inputs,
  lib,
  pkgs,
  system,
  ...
}:
let
  stateDir = "${config.home.homeDirectory}/.openclaw";
  cacheDir = "${config.home.homeDirectory}/.cache";
  tmpDir = "${stateDir}/tmp";
  # Installed by the native tools settings in tools.nix.
  openclawBin = "${config.home.homeDirectory}/.npm/bin/openclaw";
  # whisper CLI from nixpkgs (see home/desktop/packages.nix) — used by
  # tools.media.audio below.
  whisperBin = "${pkgs.openai-whisper}/bin/whisper";
  openclawSourceDir = "${config.home.homeDirectory}/Sources/github.com/openclaw/openclaw";
  gatewayPort = 18789;

  patchedConfig = "${stateDir}/openclaw-runtime.json";

  # JSON config generated by nix — same structure as nix-openclaw produced,
  # but without requiring the nix-openclaw flake input at all.
  # Run this to auth
  # `openclaw models auth login --provider openai-codex`
  openclawConfig = pkgs.writeText "openclaw.json" (
    builtins.toJSON {
      agents.defaults = {
        workspace = "${stateDir}/workspace";

        model = {
          primary = "openai/gpt-5.5";
          fallbacks = [
            "anthropic/claude-opus-4-7"
          ];
        };

        models = {
          "openai/gpt-5.5" = {
            alias = "codex";
          };

          "anthropic/claude-opus-4-7" = {
            alias = "opus";
          };
        };
      };

      gateway = {
        mode = "local";
        port = gatewayPort;
        auth.mode = "token";
        # FIXME: Reverse proxy pairing workaround. Remove when upstream fixes land.
        # https://github.com/openclaw/openclaw/issues/1679
        # https://github.com/openclaw/openclaw/issues/49293
        trustedProxies = [
          "127.0.0.1"
          "::1"
        ];
        controlUi.allowInsecureAuth = true;
      };

      channels.discord = {
        enabled = true;
        execApprovals = {
          enabled = true;
          target = "channel";
        };
      };

      approvals.exec = {
        enabled = true;
        mode = "session";
        # Keep WhatsApp out of sessionFilter for now: channels.whatsapp has
        # no execApprovals block (unlike channels.discord), so adding it
        # here would gate exec without a working approval surface.
        sessionFilter = [ "discord" ];
      };

      # Group mention triggers (channel-wide fallback used by all agents
      # via messages.groupChat.mentionPatterns). Native WhatsApp @-mentions
      # don't fire from a personal-number setup (the bot's JID is your own
      # phone, so WhatsApp's autocomplete won't surface it and openclaw's
      # self-chat safeguard suppresses mention-JID auto-triggers). Typing
      # "Lizard" (case-insensitive, word-boundary) in a group message
      # wakes the bot instead.
      messages.groupChat.mentionPatterns = [ "(?i)\\bLizard\\b" ];

      tools.exec = {
        security = "full";
        ask = "off";
      };

      tools.media.audio = {
        enabled = true;
        echoTranscript = true;
        models = [
          {
            type = "cli";
            command = whisperBin;
            args = [
              "--model"
              "turbo"
              "--model_dir"
              "${cacheDir}/whisper"
              "--output_dir"
              tmpDir
              "{{MediaPath}}"
            ];
            timeoutSeconds = 300;
          }
          {
            provider = "openai";
            model = "gpt-4o-mini-transcribe";
          }
        ];
      };

      session.reset = {
        mode = "daily";
        atHour = 4;
      };

      tools.web.search = {
        provider = "gemini";
      };

      skills.load.extraDirs = [
        "${config.home.homeDirectory}/.agents/skills"
        "${openclawSourceDir}/skills"
      ];

      # Disable slack — we only use discord and the bundled slack extension
      # is missing @slack/web-api at runtime.
      plugins.entries.slack.enabled = false;

      plugins.entries.codex.enabled = true;
    }
  );

  # Wrapper that patches config with SecretRefs and dynamic values, then execs the gateway.
  # Most secrets are injected as file-based SecretRefs so they stay out of process.env
  # and are not visible to agents via `env`. The exception is DISCORD_BOT_TOKEN —
  # the external @openclaw/discord plugin's hasDiscordConfiguredState() only
  # checks process.env.DISCORD_BOT_TOKEN, ignoring config-based SecretRefs.
  # Tracked upstream as openclaw/openclaw#77930 (regression in 2026.5.x).
  gatewayWithSecrets = pkgs.writeShellScript "openclaw-gateway-secrets" ''
    umask 077
    DOMAIN=$(cat ${config.sops.secrets.external-domain.path})
    SERVER_ID=$(cat ${config.sops.secrets.openclaw-discord-server-id.path})
    USER_ID=$(cat ${config.sops.secrets.openclaw-discord-user-id.path})
    # Fail loud rather than silently injecting allowFrom=[""] (schema-valid
    # but matches no sender → all WhatsApp DMs/groups silently dropped).
    export DISCORD_BOT_TOKEN=$(cat ${config.sops.secrets.openclaw-discord-bot-token.path})
    ${pkgs.jq}/bin/jq \
      --arg origin "https://openclaw.$DOMAIN" \
      --arg serverId "$SERVER_ID" \
      --arg userId "$USER_ID" \
      --arg gatewayTokenPath "${config.sops.secrets.openclaw-gateway-token.path}" \
      --arg discordTokenPath "${config.sops.secrets.openclaw-discord-bot-token.path}" \
      --arg geminiApiKeyPath "${config.sops.secrets.openclaw-gemini-api-key.path}" \
      --arg perplexityApiKeyPath "${config.sops.secrets.openclaw-perplexity-api-key.path}" \
      '
       .secrets.providers["sops-gateway-token"] = { source: "file", path: $gatewayTokenPath, mode: "singleValue" }
       | .secrets.providers["sops-discord-token"] = { source: "file", path: $discordTokenPath, mode: "singleValue" }
       | .secrets.providers["sops-gemini-api-key"] = { source: "file", path: $geminiApiKeyPath, mode: "singleValue" }
       | .secrets.providers["sops-perplexity-api-key"] = { source: "file", path: $perplexityApiKeyPath, mode: "singleValue" }
       | .gateway.auth.token = { source: "file", provider: "sops-gateway-token", id: "value" }
       | .channels.discord.token = { source: "env", provider: "default", id: "DISCORD_BOT_TOKEN" }
       | .plugins.entries.discord.enabled = true
       | .plugins.entries.google.enabled = true
       | .plugins.entries.google.config.webSearch.apiKey = { source: "file", provider: "sops-gemini-api-key", id: "value" }
       | .plugins.entries.perplexity.enabled = true
       | .plugins.entries.perplexity.config.webSearch.apiKey = { source: "file", provider: "sops-perplexity-api-key", id: "value" }
       | .gateway.controlUi.allowedOrigins = [$origin, "http://127.0.0.1:${toString gatewayPort}"]
       | .channels.discord.allowFrom = [$userId]
       | .channels.discord.guilds[$serverId] = {}
       | .channels.discord.execApprovals.approvers = [$userId]
       ' "${openclawConfig}" > "${patchedConfig}.tmp"
    mv "${patchedConfig}.tmp" "${patchedConfig}"
    export OPENCLAW_CONFIG_PATH="${patchedConfig}"

    exec ${openclawBin} gateway --port ${toString gatewayPort}
  '';

  steipeteTools = inputs.nix-steipete-tools.packages.${system};

  # peekaboo is darwin-only in nix-steipete-tools; on Linux only
  # summarize and sag are available.
  toolsPath = lib.makeBinPath [
    pkgs.nodejs_22
    pkgs.git
    pkgs.jq
    pkgs.ripgrep
    pkgs.curl
    pkgs.ffmpeg
    pkgs.sox
    pkgs.python3
    steipeteTools.summarize
    steipeteTools.sag
  ];

  preStartScript = pkgs.writeShellScript "openclaw-gateway-prestart" ''
    umask 077
    if [ ! -x "${openclawBin}" ]; then
      echo "openclaw not yet installed at ${openclawBin}; wait for local.tools deploy to finish" >&2
      exit 1
    fi
    ${pkgs.coreutils}/bin/mkdir -p \
      ${stateDir} \
      ${stateDir}/logs \
      ${stateDir}/workspace \
      ${tmpDir} \
      ${cacheDir}/whisper

    for plugin in @openclaw/discord @openclaw/codex; do
      if ! ${openclawBin} plugins inspect "$plugin" >/dev/null; then
        echo "Registering $plugin plugin with openclaw..."
        ${openclawBin} plugins install "$plugin"
      fi
    done
  '';
in
{
  # Gateway service via home-manager systemd user units (NixOS).
  # Note: sops-nix is a system unit (runs in stage-2 boot, long before any user
  # unit starts), so no user-level After/Wants on it is needed or possible.
  systemd.user.services.openclaw-gateway = {
    Unit = {
      Description = "OpenClaw gateway";
      After = [ "network-online.target" ];
      Wants = [ "network-online.target" ];
      StartLimitBurst = 5;
      StartLimitIntervalSec = 300;
    };
    Service = {
      ExecStartPre = "${preStartScript}";
      ExecStart = "${gatewayWithSecrets}";
      Restart = "always";
      RestartSec = 10;
      Environment = [
        "OPENCLAW_CONFIG_PATH=${patchedConfig}"
        "OPENCLAW_STATE_DIR=${stateDir}"
        "OPENCLAW_BUNDLED_SKILLS_DIR=${openclawSourceDir}/skills"
        "PATH=${toolsPath}:/run/current-system/sw/bin"
      ];
    };
    Install.WantedBy = [ "default.target" ];
  };

  # Point CLI at the same state/config the gateway uses
  home.sessionVariables = {
    OPENCLAW_STATE_DIR = stateDir;
    OPENCLAW_CONFIG_PATH = patchedConfig;
    OPENCLAW_BUNDLED_SKILLS_DIR = "${openclawSourceDir}/skills";
  };

  # Seed exec-approvals.json with full-access defaults (YOLO mode).
  # Migrate existing installs from allowlist to full.
  home.activation.openclawExecApprovals = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        EA="${stateDir}/exec-approvals.json"
        ${pkgs.coreutils}/bin/mkdir -p "${stateDir}"
        if [ ! -f "$EA" ]; then
          cat > "$EA" <<'EAJSON'
    {
      "version": 1,
      "defaults": {
        "security": "full",
        "ask": "off",
        "askFallback": "full",
        "autoAllowSkills": true
      },
      "agents": {}
    }
    EAJSON
          chmod 600 "$EA"
        else
          ${pkgs.jq}/bin/jq '.defaults = {
            security: "full",
            ask: "off",
            askFallback: "full",
            autoAllowSkills: true
          }' "$EA" > "$EA.tmp" && mv "$EA.tmp" "$EA"
        fi
  '';

  # No custom restart activation needed: when openclawConfig changes its
  # nix store path also changes, which changes gatewayWithSecrets's path,
  # which changes the unit's ExecStart. home-manager picks that up and
  # restarts the unit on activation. The launchd version on mini needed
  # an explicit hash-based restart; systemd does not.

  # a3 is headless — write the dashboard URL to a file the user can read
  # over SSH instead of trying to launch a browser.
  home.activation.openclawDashboardUrl = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    URL_FILE="${stateDir}/dashboard-url"
    ${pkgs.coreutils}/bin/mkdir -p "${stateDir}"
    TOKEN=$(${pkgs.coreutils}/bin/cat ${config.sops.secrets.openclaw-gateway-token.path} 2>/dev/null || echo "")
    if [ -n "$TOKEN" ]; then
      DOMAIN=$(${pkgs.coreutils}/bin/cat ${config.sops.secrets.external-domain.path} 2>/dev/null || echo "")
      if [ -n "$DOMAIN" ]; then
        umask 077
        echo "https://openclaw.$DOMAIN/#token=$TOKEN" > "$URL_FILE"
      fi
    fi
  '';

  sops.secrets.openclaw-discord-bot-token = {
    key = "discord/LizardBotToken";
  };

  sops.secrets.openclaw-gateway-token = {
    key = "openClaw/gatewayToken";
  };

  sops.secrets.openclaw-discord-server-id = {
    key = "discord/serverId";
  };

  sops.secrets.openclaw-discord-user-id = {
    key = "discord/userId";
  };

  sops.secrets.openclaw-gemini-api-key = {
    key = "geminiApiKey";
  };

  sops.secrets.openclaw-perplexity-api-key = {
    key = "perplexityApiToken";
  };
}
