apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-runtime-info
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
    reconcile.fluxcd.io/watch: Enabled
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: "Merge"
data:
  ARTIFACT_TAG: latest
  ENVIRONMENT: homelab
  CLUSTER_NAME: orbstack
  CLUSTER_DOMAIN: cluster.local
  ARTIFACT_SUBJECT_WORKFLOW: push-artifact
  ARTIFACT_SUBJECT_GIT_REF: refs/heads/main