apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 10m
  sourceRef:
    kind: OCIRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./clusters/orbstack/cluster-policies
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute: {}
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: kyverno
      namespace: flux-system