apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-flux-sa
spec:
  rules:
  - name: generate-flux-sa
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              toolkit.fluxcd.io/tenant: "?*"
    generate:
      generateExisting: true
      apiVersion: v1
      kind: ServiceAccount
      name: "{{request.object.metadata.labels.\"toolkit.fluxcd.io/tenant\"}}"
      namespace: "{{request.object.metadata.name}}"
      synchronize: false
      data:
        metadata:
          labels:
            toolkit.fluxcd.io/tenant: "{{request.object.metadata.labels.\"toolkit.fluxcd.io/tenant\"}}"
  - name: generate-flux-rolebinding
    match:
      any:
      - resources:
          kinds:
          - Namespace
          selector:
            matchLabels:
              toolkit.fluxcd.io/tenant: "?*"
    generate:
      generateExisting: true
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: "{{request.object.metadata.labels.\"toolkit.fluxcd.io/tenant\"}}"
      namespace: "{{request.object.metadata.name}}"
      synchronize: false
      data:
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: admin
        subjects:
        - kind: ServiceAccount
          name: "{{request.object.metadata.labels.\"toolkit.fluxcd.io/tenant\"}}"
          namespace: "{{request.object.metadata.name}}"