{
  imports = [
    ../../../../home/atuin.nix
    ../../../../home/bash.nix
    ../../../../home/bat.nix
    ../../../../home/brctl.nix
    ../../../../home/btop.nix
    ../../../../home/carapace.nix
    ../../../../home/claude-settings.nix
    ../../../../home/direnv.nix
    ../../../../home/firefox-darwin.nix
    ../../../../home/firefox-darwin.nix
    ../../../../home/fish.nix
    ../../../../home/fzf.nix
    ../../../../home/ghorg.nix
    ../../../../home/git
    ../../../../home/go.nix
    ../../../../home/gpg.nix
    ../../../../home/gwq.nix
    ../../../../home/hammerspoon
    ../../../../home/home-session-vars.nix
    ../../../../home/kitty
    ../../../../home/lsd.nix
    ../../../../home/mpv.nix
    ../../../../home/nextdns.nix
    ../../../../home/nix-registry.nix
    ../../../../home/nixvim
    ../../../../home/nixvim.nix
    ../../../../home/nixvim/plugins/gpg-nvim
    ../../../../home/npm.nix
    ../../../../home/nushell.nix
    ../../../../home/packages-local.nix
    ../../../../home/packages-overlays.nix
    ../../../../home/parallel.nix
    ../../../../home/pi-models.nix
    ../../../../home/quit-mac-mouse-fix.nix
    ../../../../home/ranger.nix
    ../../../../home/rbw.nix
    ../../../../home/rebuild-diff.nix
    ../../../../home/safari.nix
    ../../../../home/sops-secrets.nix
    ../../../../home/ssh.nix
    ../../../../home/starship
    ../../../../home/summarize.nix
    ../../../../home/syncthing.nix
    ../../../../home/tmux.nix
    ../../../../home/treefmt.nix
    ../../../../home/xattr.nix
    ../../../../home/yazi.nix
    ../../../../home/z-lua.nix
    ../../../../home/zsh.nix
    ../../../../modules/flags
    ../../../../modules/home/dock
    ../../../../modules/home/launchd
    ../../../../modules/home/nextdns-mgmt
    ../../../../modules/home/reposync
    ../../../../modules/home/settings-daemon
    ../../../../modules/home/syncthing-mgmt
    ../../../../modules/home/tools
    ../../../../modules/inventory
    ../../../../secrets/sops-nix.nix
    ./dock.nix
    ./flags.nix
    ./packages-darwin.nix
    ./packages-local.nix
    ./packages.nix
    ./settings-daemon.nix
    ./sops.nix
    ./tmux.nix
    ./tools.nix
  ];
}
