{
  imports = [
    ../../../darwin/home/flags.nix
    ../../../modules/home/manual-packages
    ./manual-packages.nix
    ../../../darwin/home/nixvim.nix
    ../../../darwin/home/packages.nix
    ../../../home/amethyst
    # ../../../home/bash.nix
    ../../../home/bat.nix
    ../../../home/btop.nix
    ../../../home/direnv.nix
    ../../../home/ghostty.nix
    ../../../home/git
    ../../../home/go.nix
    ../../../home/hammerspoon
    ../../../home/home-session-vars.nix
    ../../../home/kitty
    ../../../home/lsd.nix
    ../../../home/mpv.nix
    ../../../home/nixvim
    ../../../home/nixvim/plugins/copilot-lua
    ../../../home/npm.nix
    ../../../home/pass.nix
    ../../../home/rebuild-diff.nix
    ../../../home/safari.nix
    ../../../home/shell.nix
    ../../../home/starship
    ../../../home/syncthing.nix
    ../../../home/tmux.nix
    ../../../home/vscode.nix
    ../../../home/yt-dlp.nix
    ../../../modules/flags
  ];
}
