{
  imports = [
    ../../../home/amethyst
    ../../../home/atuin.nix
    ../../../home/bat.nix
    ../../../home/btop.nix
    ../../../home/carapace.nix
    ../../../home/claude.nix
    ../../../home/direnv.nix
    ../../../home/fish.nix
    ../../../home/flags.nix
    ../../../home/fzf.nix
    ../../../home/gemini.nix
    ../../../home/ghorg.nix
    ../../../home/ghostty.nix
    ../../../home/giffer.nix
    ../../../home/git
    ../../../home/go.nix
    ../../../home/hammerspoon
    ../../../home/home-session-vars.nix
    ../../../home/jujutsu.nix
    ../../../home/kitty
    ../../../home/lsd.nix
    ../../../home/mpv.nix
    ../../../home/nixvim
    ../../../home/nixvim/plugins/codediff
    ../../../home/nixvim/plugins/gpg-nvim
    ../../../home/nixvim.nix
    ../../../home/npm.nix
    ../../../home/nushell.nix
    ../../../home/packages-darwin.nix
    ../../../home/pass.nix
    ../../../home/ranger.nix
    ../../../home/rebuild-diff.nix
    ../../../home/safari.nix
    ../../../home/scripts.nix
    ../../../home/sops.nix
    ../../../home/starship
    ../../../home/syncthing-ignore.nix
    ../../../home/taskwarrior.nix
    ../../../home/tmux.nix
    ../../../home/treefmt.nix
    ../../../home/vscode.nix
    ../../../home/yt-dlp.nix
    ../../../home/z-lua.nix
    ../../../home/zsh.nix
    ../../../modules/flags
    ../../../modules/home/tools
    ../../../home/packages.nix
    ../../../home/tools.nix
  ];
}
