{
  imports = [
    ../../../../darwin/darwin.nix
    ../../../../darwin/flags.nix
    ../../../../darwin/fonts.nix
    ../../../../darwin/no-dock-restart.nix
    ../../../../darwin/security.nix
    ../../../../darwin/shell.nix
    ../../../../darwin/sudo.nix
    ../../../../darwin/system.nix
    ../../../../darwin/users.nix
    ../../../../modules/darwin/pam
    ../../../../modules/darwin/sudo
    ../../../../modules/flags
    ../../../../modules/inventory
    ../../../../system/documentation.nix
    ../../../../system/nix.nix
    ./accessibility.nix
    ./fulldiskaccess.nix
    ./homebrew.nix
    ./users.nix
  ];
}
