{
  imports = [
    ../../darwin/darwin.nix
    ../../darwin/fonts.nix
    ../../darwin/shell.nix
    ../../darwin/sudo.nix
    ../../darwin/syncthing.nix
    ../../darwin/system.nix
    ../../modules/darwin/beszel-agent
    ../../modules/darwin/beszel-mgmt
    ../../modules/darwin/dnsmasq
    ../../modules/darwin/dock
    ../../modules/darwin/doh-server
    ../../modules/darwin/launchd-service
    ../../modules/darwin/logrotate
    ../../modules/darwin/pam
    ../../modules/darwin/pmset
    ../../modules/darwin/sharing
    ../../modules/darwin/stubby
    ../../modules/darwin/sudo
    ../../modules/darwin/tmux-rebuild
    ../../modules/flags
    ../../modules/secrets
    ../../modules/shared/arr-mgmt
    ../../modules/shared/jellyfin-mgmt
    ../../modules/shared/nextdns-mgmt
    ../../modules/shared/uptime-kuma-mgmt
    ../../system/documentation.nix
    ../../system/nix.nix
    ./beszel.nix
    ./bin.nix
    ./uptime-kuma
    ./dns.nix
    ./dock.nix
    ./doh.nix
    ./git.nix
    ./homebrew.nix
    ./http.nix
    ./jellyfin
    ./logrotate.nix
    ./media
    ./miniserve.nix
    ./nextdns
    ./nix.nix
    ./ollama.nix
    ./openssh.nix
    ./packages.nix
    ./podsync
    ./power.nix
    ./sharing.nix
    ./stash
    ./sudo.nix
    ./system.nix
    ./tailscale.nix
    ./tmux-rebuild.nix
  ];
}
