{
  imports = [
    ./beszel.nix
    ./configuration.nix
    ./dns.nix
    ./forgejo.nix
    ./http.nix
    ./immich.nix
    ./media
    ./miniserve.nix
    ./navidrome.nix
    ./networking.nix
    ./nextdns.nix
    ./nixpkgs.nix
    ./ollama.nix
    ./open-webui.nix
    ./power-monitoring.nix
    ./remote-build.nix
    ./reposync.nix
    ./security.nix
    ./storage-disk.nix
    ./syncthing-mgmt.nix
    ./uptime-kuma.nix
  ];
}
