apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwebui
  namespace: openwebui
  annotations:
    # Use Caddy ingress controller
    kubernetes.io/ingress.class: caddy
spec:
  rules:
  - host: open-webui.openwebui.svc.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              number: 8080