apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - sealed-secret.yaml  # Create with kubeseal after sealed-secrets is deployed
