---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openwebui-config
  namespace: openwebui
spec:
  encryptedData:
    external-domain: AgCzHZTyaZgJD/YAwZWHFe+iER6i2Xo7PL1TVbdqaFdehB4WdKOyPfmH4Rw4ykfH/PXkFVsrRwPXNUcvp1RIt7kfoyYA/REO8ewJRt2Ie8Iq5O5ZR418mbfPKbzhHZJ4o5fKYarC/OFLRuZTfvlhk4CBxfRqU4ahgMopQw2Sjt3b52anFPZ8ZLfhfTRo0+EgoGY4mUVmcgyEozTat++Pklb7OkaiTOcWqgyoxWQUCOcHqRh/KPJY+XOXwLJbVnsWqIyTtL7hN5x/tRsJj17qkzpFw+462uCqYvFA0CN5oGdlNAi//yUsqoe/XhwyjKiCgFS3m4LLB3xdUdjJsAaCHpC0k8JLgF6CAOcZF04kRQEsimO/ofrPpIfEpMZ7T7n+jWG6NXc+TCgtSFwpL6WFtdBk5zItXeNzvwBXQ1SkCQsWypRP1sSCj1YiafEL9U3xjvHqQ5WlikjWXJ2VNopSfCPKyLuDWhVAwDl0HQZnIiaPVOV0OWVvQZ1MQPrvJc1sCYhpLKSIpKwqPSuH2oSlJERfIX8bMOxI4m8sIEczTRqSXKhUnGOK1XGZs8+1nslxcMERqbKgN1r5fz61eplL9O6zYhd6I1XAJV9RBGSGGa18tagxi3H2DAHvbVxEFcVL3IMEdW+Rc6G5Tb1ABLoKBBdx8tu9+ER/m38jRj9JxXPXalgyC3kqQysMHZpnR/VE5P4lzrY5lGwINDKBPpDR
  template:
    metadata:
      creationTimestamp: null
      name: openwebui-config
      namespace: openwebui
