{
  imports = [
    ../../../darwin/darwin.nix
    ../../../darwin/dns-clear.nix
    ../../../darwin/flags.nix
    ../../../darwin/fonts.nix
    ../../../darwin/git.nix
    ../../../darwin/homebrew.nix
    ../../../darwin/init.nix
    ./login-items.nix
    ../../../darwin/nextdns.nix
    ../../../darwin/nix.nix
    ../../../darwin/no-dock-restart.nix
    ../../../darwin/security.nix
    ../../../darwin/shell.nix
    ../../../darwin/stash
    ../../../darwin/sudo.nix
    ../../../darwin/syncthing-mgmt.nix
    ../../../darwin/syncthing.nix
    ../../../darwin/system.nix
    ../../../darwin/taskwarrior-notify.nix
    ../../../darwin/taskwarrior-sync.nix
    ../../../darwin/users.nix
    ../../../darwin/xattr.nix
    ../../../modules/darwin/dock
    ../../../modules/darwin/launchd
    ../../../modules/darwin/nextdns-mgmt
    ../../../modules/darwin/taskwarrior-notify
    ../../../modules/darwin/pam
    ../../../modules/darwin/reposync
    ../../../modules/darwin/sudo
    ../../../modules/darwin/syncthing-mgmt
    ../../../modules/flags
    ../../../system/documentation.nix
    ../../../system/nix.nix
    ../../../system/sops-secrets.nix
    ../../../system/reposync.nix
    ../../Ivans-MacBook-Air/darwin/dock.nix
    ../../Ivans-MacBook-Air/darwin/reposync.nix
    ../../Ivans-MacBook-Air/darwin/users.nix
];
}
