{
  imports = [
    ../../../darwin/darwin.nix
    ../../../darwin/flags.nix
    ../../../darwin/fonts.nix
    ../../../darwin/git.nix
    ../../../darwin/homebrew.nix
    ../../../darwin/init.nix
    ../../../darwin/nix.nix
    ../../../darwin/no-dock-restart.nix
    ../../../darwin/security.nix
    ../../../darwin/shell.nix
    ../../../darwin/sudo.nix
    ../../../darwin/system.nix
    ../../../darwin/users.nix
    ../../../modules/darwin/launchd
    ../../../modules/darwin/nextdns
    ../../../modules/darwin/pam
    ../../../modules/darwin/sudo
    ../../../modules/flags
    ../../../system/documentation.nix
    ../../../system/nix.nix
    ../../../system/sops-secrets.nix
    ../../Ivans-MacBook-Air/darwin/users.nix
    ./accessibility.nix
    ./dns.nix
    ./login-items.nix
  ];
}
