{
  imports = [
    ../../../darwin/amethyst.nix
    ../../../darwin/darwin.nix
    ../../../darwin/dns-clear.nix
    ../../../darwin/dotfiles-sync.nix
    ../../../darwin/flags.nix
    ../../../darwin/fonts.nix
    ../../../darwin/hammerspoon.nix
    ../../../darwin/init.nix
    ../../../darwin/mac-mouse-fix.nix
    ../../../darwin/nextdns.nix
    ../../../darwin/nix.nix
    ../../../darwin/no-dock-restart.nix
    ../../../darwin/rebuild-terminal.nix
    ../../../darwin/security.nix
    ../../../darwin/shell.nix
    ../../../darwin/stats.nix
    ../../../darwin/sudo.nix
    ../../../darwin/syncthing.nix
    ../../../darwin/syncthing-cleaner.nix
    ../../../darwin/system.nix
    ../../../darwin/users.nix
    ../../../darwin/xattr.nix
    ../../../modules/darwin/dock
    ../../../modules/darwin/launchd
    ../../../modules/darwin/nextdns-mgmt
    ../../../modules/darwin/pam
    ../../../modules/darwin/rebuild-terminal
    ../../../modules/darwin/sudo
    ../../../modules/darwin/syncthing-cleaner
    ../../../modules/darwin/syncthing-mgmt
    ../../../modules/flags
    ../../../system/documentation.nix
    ../../../system/nix.nix
    ../../../system/scripts
    ../../../darwin/git.nix
    ../../../darwin/homebrew.nix
    ../../../darwin/stash
    ../../../darwin/syncthing-mgmt.nix
    ../../Ivans-MacBook-Air/darwin/dock.nix
    ../../Ivans-MacBook-Air/darwin/users.nix
  ];
}
