{
  imports = [
    ../../../../darwin/syncthing.nix
    ../../../../modules/darwin/dnsmasq
    ../../../../modules/darwin/doh-server
    ../../../../modules/darwin/logrotate
    ../../../../modules/darwin/pmset
    ../../../../modules/darwin/sharing
    ../../../../modules/darwin/stubby
    ../../../../modules/darwin/sudo
    ../../../../modules/darwin/tmux-rebuild
    ../../../../modules/flags
    ../../../../modules/secrets
    ./bin.nix
    ./dns.nix
    ./doh.nix
    ./git.nix
    ./homebrew.nix
    ./tailscale.nix
    ./http.nix
    ./logrotate.nix
    ./miniserve.nix
    # ./netdata.nix
    ./nix.nix
    ./openssh.nix
    ./packages.nix
    ./power.nix
    ./sharing.nix
    ./sudo.nix
    ./system.nix
    ./tmux-rebuild.nix
  ];
}
