{
  imports = [
    ../../../home/atuin.nix
    ../../../home/bat.nix
    ../../../home/brctl.nix
    ../../../home/btop.nix
    ../../../home/carapace.nix
    ../../../home/claude-settings.nix
    ../../../home/direnv.nix
    ../../../home/firefox-darwin.nix
    ../../../home/fish.nix
    ../../../home/flags.nix
    ../../../home/fzf.nix
    ../../../home/ghorg.nix
    ../../../home/git
    ../../../home/go.nix
    ../../../home/gpg.nix
    ../../../home/gwq.nix
    ../../../home/hammerspoon
    ../../../home/home-session-vars.nix
    ../../../home/kitty
    ../../../home/lsd.nix
    ../../../home/mpv.nix
    ../../../home/nextdns.nix
    ../../../home/nix-registry.nix
    ../../../home/nixvim
    ../../../home/nixvim.nix
    ../../../home/nixvim/plugins/gpg-nvim
    ../../../home/notifications.nix
    ../../../home/npm.nix
    ../../../home/nushell.nix
    ../../../home/packages-darwin.nix
    ../../../home/packages-local.nix
    ../../../home/packages-overlays.nix
    ../../../home/packages.nix
    ../../../home/pass.nix
    ../../../home/ranger.nix
    ../../../home/rbw.nix
    ../../../home/rebuild-diff.nix
    ../../../home/safari.nix
    ../../../home/sops.nix
    ../../../home/starship
    ../../../home/summarize.nix
    ../../../home/syncthing-mgmt.nix
    ../../../home/syncthing.nix
    ../../../home/tmux.nix
    ../../../home/tools.nix
    ../../../home/treefmt.nix
    ../../../home/xattr.nix
    ../../../home/z-lua.nix
    ../../../home/zsh.nix
    ../../../modules/flags
    ../../../modules/home/dock
    ../../../modules/home/launchd
    ../../../modules/home/nextdns-mgmt
    ../../../modules/home/notifications
    ../../../modules/home/reposync
    ../../../modules/home/settings-daemon
    ../../../modules/home/syncthing-mgmt
    ../../../modules/home/tools
    ../../../modules/inventory
    ../../Ivans-MacBook-Air/home/dock.nix
    ../../Ivans-MacBook-Air/home/packages.nix
    ../../Ivans-MacBook-Air/home/reposync.nix
    ./settings-daemon.nix
  ];
}
