{
  imports = [
    ../../../home/amethyst
    ../../../home/atuin.nix
    ../../../home/bat.nix
    ../../../home/brctl.nix
    ../../../home/btop.nix
    ../../../home/carapace.nix
    ../../../home/claude.nix
    ../../../home/direnv.nix
    ../../../home/dns-clear.nix
    ../../../home/fish.nix
    ../../../home/flags.nix
    ../../../home/fzf.nix
    ../../../home/ghorg.nix
    ../../../home/ghostty.nix
    ../../../home/giffer.nix
    ../../../home/git
    ../../../home/go.nix
    ../../../home/gpg.nix
    ../../../home/gwq.nix
    ../../../home/hammerspoon
    ../../../home/home-session-vars.nix
    ../../../home/jujutsu.nix
    ../../../home/kitty
    ../../../home/lsd.nix
    ../../../home/mpv.nix
    ../../../home/nextdns.nix
    ../../../home/nix-registry.nix
    ../../../home/nixvim
    ../../../home/nixvim.nix
    ../../../home/nixvim/plugins/codediff
    ../../../home/nixvim/plugins/gpg-nvim
    ../../../home/npm.nix
    ../../../home/nushell.nix
    ../../../home/obsidian-darwin.nix
    ../../../home/packages-darwin.nix
    ../../../home/packages.nix
    ../../../home/pass.nix
    ../../../home/quit-mac-mouse-fix.nix
    ../../../home/ranger.nix
    ../../../home/rebuild-diff.nix
    ../../../home/safari.nix
    ../../../home/sops.nix
    ../../../home/starship
    ../../../home/stash
    ../../../home/syncthing-ignore.nix
    ../../../home/syncthing-mgmt.nix
    ../../../home/syncthing.nix
    ../../../home/taskwarrior-notify.nix
    ../../../home/taskwarrior-sync.nix
    ../../../home/taskwarrior.nix
    ../../../home/tmux.nix
    ../../../home/tools.nix
    ../../../home/treefmt.nix
    ../../../home/vscode.nix
    ../../../home/xattr.nix
    ../../../home/yt-dlp.nix
    ../../../home/zoxide.nix
    ../../../home/zsh.nix
    ../../../modules/flags
    ../../../modules/home/dock
    ../../../modules/home/launchd
    ../../../modules/home/nextdns-mgmt
    ../../../modules/home/reposync
    ../../../modules/home/syncthing-mgmt
    ../../../modules/home/taskwarrior-notify
    ../../../modules/home/tools
    ../../Ivans-MacBook-Air/home/dock.nix
    ../../Ivans-MacBook-Air/home/reposync.nix
  ];
}
