{
  imports = [
    # ../../../home/bash.nix
    ../../../darwin/home/activation.nix
    ../../../darwin/home/flags.nix
    ../../../darwin/home/nixvim.nix
    ../../../darwin/home/packages.nix
    ../../../home/amethyst
    ../../../home/bat.nix
    ../../../home/btop.nix
    ../../../home/claude.nix
    ../../../home/direnv.nix
    ../../../home/ghostty.nix
    ../../../home/git.nix
    ../../../home/go.nix
    ../../../home/hammerspoon
    ../../../home/home-session-vars.nix
    ../../../home/kitty
    ../../../home/lsd.nix
    ../../../home/mpv.nix
    ../../../home/nixvim
    ../../../home/nixvim/plugins/copilot-lua
    ../../../home/npm.nix
    ../../../home/pass.nix
    ../../../home/rebuild-diff.nix
    ../../../home/scripts.nix
    ../../../home/shell.nix
    ../../../home/starship
    ../../../home/syncthing.nix
    ../../../home/taskwarrior.nix
    ../../../home/tmux.nix
    ../../../home/vscode.nix
    ../../../home/yt-dlp.nix
    ../../../modules/flags
    ../../../modules/secrets
    ./packages.nix
  ];
}
