{
  imports = [
    ./audiobookshelf
    ./beszel.nix
    ./bin.nix
    ./download-youtube
    ./forgejo
    ./healthchecks
    ./infracheck.nix
    ./jellyfin
    # ./logscanner.nix
    ./matrix
    ./media
    ./miniserve.nix
    ./monitoring
    ./navidrome
    ./ollama.nix
    ./open-webui.nix
    ./perlite
    ./podservice
    ./podsync
    ./reposync.nix
    ./restart-unhealthy.nix
    ./stash
    ./stash-media
    ./syncthing-mgmt.nix
    ./taskchampion-sync-server.nix
    ./taskwarrior-web.nix
    ./taskweb.nix
    ./textcast
    ./uptime-kuma
  ];
}
