{
  imports = [
    ./beszel.nix
    ./download-youtube
    ./forgejo
    ./jellyfin
    ./media
    ./miniserve.nix
    ./navidrome
    ./ollama.nix
    ./open-webui.nix
    ./podservice
    ./reposync.nix
    ./restart-unhealthy.nix
    ./stash-media
    ./syncthing-mgmt.nix
    ./textcast
    ./uptime-kuma
  ];
}
