{
  imports = [
    ../../../modules/flags
    ../../../modules/nixos/rebuild-daemon
    ../../../modules/nixos/syncthing-cleaner
    ../../../modules/nixos/syncthing-mgmt
    ../../../nixos/chromium.nix
    ../../../nixos/keyboard.nix
    ../../../system/nix.nix
    ../../../system/rebuild-daemon.nix
    ../../../system/scripts
    ./bluetooth.nix
    ./boot.nix
    ./configuration.nix
    ./cryptenroll.nix
    ./default-apps.nix
    ./dotfiles-sync.nix
    ./desktop.nix
    ./fonts.nix
    ./jovian.nix
    ./networking.nix
    ./nixpkgs.nix
    ./remote-build.nix
    ./sd-card.nix
    ./security.nix
    ../../../nixos/sudo.nix
    ./syncthing-cleaner.nix
    ./syncthing-mgmt.nix
    ./tpm2.nix
    ./user.nix
  ];
}
