{
  imports = [
    # ../../../home/aider.nix
    # ../../../home/codex.nix
    # ../../../home/nixvim/plugins/copilot-lua
    # ./prevent-sleep.nix
    ../../../home/aichat-server.nix
    ../../../home/aichat.nix
    ../../../home/amethyst
    ../../../home/bat.nix
    ../../../home/btop.nix
    ../../../home/ccstatusline.nix
    ../../../home/claude.nix
    ../../../home/direnv.nix
    ../../../home/gemini.nix
    ../../../home/ghorg.nix
    ../../../home/ghostty.nix
    ../../../home/git
    ../../../home/go.nix
    ../../../home/gpg.nix
    ../../../home/hammerspoon
    ../../../home/home-session-vars.nix
    ../../../home/jujutsu.nix
    ../../../home/k9s.nix
    ../../../home/kitty
    ../../../home/lsd.nix
    ../../../home/mpv.nix
    ../../../home/nixvim
    ../../../home/nixvim/plugins/gen-nvim
    ../../../home/nixvim/plugins/octo-nvim
    ../../../home/nixvim/plugins/unified-nvim
    ../../../home/nushell.nix
    ../../../home/pass.nix
    ../../../home/pay-respects.nix
    ../../../home/pgcli.nix
    ../../../home/pyenv.nix
    ../../../home/rebuild-diff.nix
    ../../../home/safari.nix
    ../../../home/scripts.nix
    ../../../home/shell.nix
    ../../../home/sops.nix
    ../../../home/ssh.nix
    ../../../home/starship
    ../../../home/syncthing-ignore.nix
    ../../../home/terraform.nix
    ../../../home/tmux.nix
    ../../../home/tweety.nix
    ../../../home/vscode.nix
    ../../../home/yamlint.nix
    ../../../home/yt-dlp.nix
    ../../../home/zellij.nix
    ../../../modules/flags
    ../../../modules/home/packages
    ./firefox.nix
    ./flags.nix
    ./manual-packages.nix
    ./nixvim.nix
    ./packages.nix
    ./programs.nix
  ];
}
