{
  imports = [
    ../../../home/atuin.nix
    ../../../home/bat.nix
    ../../../home/bitwarden.nix
    ../../../home/btop.nix
    ../../../home/claude-settings.nix
    ../../../home/direnv.nix
    ../../../home/fish.nix
    ../../../home/fzf.nix
    ../../../home/gemini-settings.nix
    ../../../home/ghorg.nix
    ../../../home/git
    ../../../home/go.nix
    ../../../home/gpg.nix
    ../../../home/gwq.nix
    ../../../home/hammerspoon
    ../../../home/home-session-vars.nix
    ../../../home/k9s.nix
    ../../../home/kitty
    ../../../home/lsd.nix
    ../../../home/mpv.nix
    ../../../home/nix-registry.nix
    ../../../home/nixvim
    ../../../home/nixvim/plugins/octo-nvim
    ../../../home/notifications.nix
    ../../../home/opentofu.nix
    ../../../home/nushell.nix
    ../../../home/packages-darwin.nix
    ../../../home/packages.nix
    ../../../home/pass.nix
    ../../../home/pay-respects.nix
    ../../../home/pgcli.nix
    ../../../home/quit-mac-mouse-fix.nix
    ../../../home/ranger.nix
    ../../../home/rebuild-diff.nix
    ../../../home/safari.nix
    ../../../home/sops.nix
    ../../../home/ssh.nix
    ../../../home/starship
    ../../../home/syncthing.nix
    ../../../home/terraform.nix
    ../../../home/terragrunt.nix
    ../../../home/tmux.nix
    ../../../home/treefmt.nix
    ../../../home/yamlint.nix
    ../../../home/z-lua.nix
    ../../../home/zsh.nix
    ../../../modules/flags
    ../../../modules/home/dock
    ../../../modules/home/launchd
    ../../../modules/home/notifications
    ../../../modules/home/reposync
    ../../../modules/home/settings-daemon
    ../../../modules/home/syncthing-mgmt
    ../../../modules/home/tools
    ../../../modules/inventory
    ./container.nix
    ./dock.nix
    ./firefox.nix
    ./flags.nix
    ./nixvim.nix
    ./packages.nix
    ./programs.nix
    ./reposync.nix
    ./settings-daemon.nix
    ./syncthing-mgmt.nix
    ./tools.nix
  ];
}
