{ pkgs, ... }:
{
  home.packages = with pkgs; [
    (python313.withPackages (
      ps: with ps; [
        grip
        (jira.overridePythonAttrs (old: {
          propagatedBuildInputs = (old.propagatedBuildInputs or [ ]) ++ old.optional-dependencies.cli;
        }))
      ]
    ))
    (wrapHelm kubernetes-helm { plugins = with pkgs.kubernetes-helmPlugins; [ helm-secrets ]; })
    # jsonnet # ruby3.3-nokogiri build fails: fatal error: 'nokogiri_gumbo.h' file not found
    # kcat # avro-c++ build fails with fmt 11.2.0: error: no matching member function for call to 'format' in fmt::formatter<avro::Type>
    flarectl
    argocd
    obs
    obsidian-cli
    diff-long-lines
    aws-sso-cli
    aws-sso-creds
    awscli2
    backup-home
    bat
    cargo
    claude-code-logs
    cloudflared
    confluence
    confluent-cli
    coreutils
    crane
    curlie
    defaultbrowser
    databricks-cli
    delta
    devbox
    devcontainer
    docker-client
    docker-compose
    docker-credential-helpers
    dockutil # macOS related CLI
    doggo
    duf
    dust
    eks-node-viewer
    erdtree
    exiftool
    find-grep
    genpass
    ggh
    gh-pr
    git-message
    git-pull-all
    git-worktree-init
    gitleaks
    glow
    go-grip
    gofumpt
    golangci-lint
    google-cloud-sdk
    grpcui
    grpcurl
    gum
    hadolint
    hclfmt
    home-manager
    iam-policy-json-to-terraform
    imagemagick
    infra
    infracost
    jcli
    jq
    k8sgpt
    kail
    kdash
    krew
    kubecolor
    kubectl
    kubectl-ai
    kubectl-images
    kubectl-view-secret
    kubectx
    kubepug
    kustomize
    launchd-mgmt
    lsd
    magic-wormhole
    mariadb
    mkcd
    mkpasswd
    mongosh
    mycli
    nh # https://github.com/nix-community/nh
    nixfmt-rfc-style
    nixpkgs-darwin-master.cursor-cli
    nixpkgs-darwin-master.fluxcd
    nixpkgs-darwin-master.jira-cli-go
    nixpkgs-darwin-master-opencode.opencode
    nodejs
    nodePackages.aws-cdk
    nodePackages.prettier
    gh-notifications
    opentofu
    opsy
    oras
    parallel
    perplexity
    pigz
    pnpm
    nixpkgs-darwin-master.poetry
    popeye
    postgresql
    pblock
    pre-commit
    pv
    pyenv-nix-install
    rabbitmq-server # Needed for the CLI
    rabbitmqadmin-ng # Overlay
    rclone
    redis
    rust-analyzer
    rustc
    sesh
    dns
    jira-custom
    shellcheck
    shfmt
    skopeo
    slack-cli-go
    smctemp
    sops
    ssh-to-age
    sshpass
    ssm-session-manager-plugin
    stylua
    poweroff
    dotfiles
    settings
    syncthing-mgmt
    terraformer
    terragrunt-atlantis-config
    temporal
    temporal-cli
    tmux-spawn
    tree
    treefmt
    username # Installed as flake
    uv
    vault
    vault-auth
    vkv
    vals
    watchman
    watchman-make
    watchman-rebuild
    wget
    yq
    zoxide
  ];
}
