{ ... }:

{
  imports = [
    ../../../home/atuin.nix
    ../../../home/chromium.nix
    ../../../home/claude-settings.nix
    ../../../home/claude.nix
    ../../../home/codex.nix
    ../../../home/fish.nix
    ../../../home/fzf.nix
    ../../../home/gemini-settings.nix
    ../../../home/ghorg.nix
    ../../../home/ghostty.nix
    ../../../home/git
    ../../../home/go.nix
    ../../../home/gwq.nix
    ../../../home/home-session-vars.nix
    ../../../home/jujutsu.nix
    ../../../home/kitty
    ../../../home/lsd.nix
    ../../../home/mpv.nix
    ../../../home/nextdns.nix
    ../../../home/nix-registry.nix
    ../../../home/nixos/packages.nix
    ../../../home/nixvim
    ../../../home/nixvim/plugins/codediff
    ../../../home/nixvim/plugins/gpg-nvim
    ../../../home/npm.nix
    ../../../home/nushell.nix
    ../../../home/obsidian.nix
    ../../../home/packages.nix
    ../../../home/pi-models.nix
    ../../../home/ranger.nix
    ../../../home/rebuild-diff.nix
    ../../../home/sops.nix
    ../../../home/ssh.nix
    ../../../home/starship
    ../../../home/syncthing-ignore.nix
    ../../../home/tmux.nix
    ../../../home/treefmt.nix
    ../../../home/tweety.nix
    ../../../home/z-lua.nix
    ../../../home/zsh.nix
    ../../../modules/flags
    ../../../modules/home/beszel-mgmt
    ../../../modules/home/jellyfin-mgmt
    ../../../modules/home/launchd
    ../../../modules/home/nextdns-mgmt
    ../../../modules/home/tools
    ../../../modules/home/uptime-kuma-mgmt
    ./desktop
    ./server
  ];
}
