{
  imports = [
    ../../../system/sops-secrets.nix
    ../../../darwin/amethyst.nix
    ../../../darwin/darwin.nix
    ../../../darwin/dock.nix
    ../../../darwin/flags.nix
    ../../../darwin/fonts.nix
    ../../../darwin/mos.nix
    ../../../darwin/stats.nix
    ../../../darwin/nextdns.nix
    ../../../darwin/nix.nix
    ../../../darwin/security.nix
    ../../../darwin/shell.nix
    ../../../darwin/sudo.nix
    ../../../darwin/system.nix
    ../../../modules/darwin/dock
    ../../../modules/darwin/launchd
    ../../../modules/darwin/nextdns-mgmt
    ../../../modules/darwin/pam
    ../../../modules/darwin/sudo
    ../../../modules/darwin/syncthing-mgmt
    ../../../modules/darwin/rebuild-daemon
    ../../../modules/flags
    ../../../system/documentation.nix
    ../../../system/nix.nix
    ../../../system/rebuild-daemon.nix
    ../../../system/scripts
    ../../../darwin/no-dock-restart.nix
    ./git.nix
    ./homebrew.nix
    ./podservice
    ./syncthing-mgmt.nix
    ./textcast
  ];
}
