name: push-k8s-artifact

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'machines/Ivans-Mac-mini/darwin/server/k8s/**'
    tags:
      - '*'

jobs:
  flux-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # for pushing
      id-token: write # for signing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install flux
        uses: controlplaneio-fluxcd/distribution/actions/setup@main
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare tags
        id: prep
        run: |
          TAG=latest
          VERSION="${{ github.ref_name }}-${GITHUB_SHA::8}"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=latest-stable
            VERSION="${{ github.ref_name }}"
          fi
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Push artifact
        uses: controlplaneio-fluxcd/distribution/actions/push@main
        id: push
        with:
          repository: ghcr.io/${{ github.repository }}
          path: "./machines/Ivans-Mac-mini/darwin/server/k8s"
          diff-tag: ${{ steps.prep.outputs.tag }}
          tags: ${{ steps.prep.outputs.version }}
      - name: Sign artifact
        if: steps.push.outputs.pushed == 'true'
        run: cosign sign --yes $DIGEST_URL
        env:
          DIGEST_URL: ${{ steps.push.outputs.digest-url }}