email: ENC[AES256_GCM,data:/lZwlnfVzI+IGDxgKr2E6CrxliQBUanZ,iv:fuSEAGB4W45FTvEx7U9UXn84msJ9qK0ULkTCmZ6ZKz4=,tag:O2gKK09pPMF8sCEQGh8/yg==,type:str]
letsEncryptEmail: ENC[AES256_GCM,data:nW7oVaB3U8pzUlwDdUyi7OgiuT0VNuZECC8=,iv:f+oIBOjYAseHNgPPGRqUeRIiqb2MIxrEBc5MO9zyIeY=,tag:f3EKXUDLT1ie7D4uBE7Ryw==,type:str]
nextDNSID: ENC[AES256_GCM,data:6Czx4n8B,iv:9zcLyECUGcCC8sgEhxOcTJgDWvOK5YLkvGyBz387N/Q=,tag:GlOhWhBBN5dqCw8ykF2gEA==,type:str]
nextDnsApiKey: ENC[AES256_GCM,data:d4giHjpi3cdQyMvWvcmdQhnEGad7WEI/jJ3SM2a3fmbOuqZaj2ehPw==,iv:mt88X249LAdYFXwgXvNDe86+4LNfib635I0lKHmruSg=,tag:UqjKp5ic0Szcuk7Tt/5MUg==,type:str]
nextDnsServer1: ENC[AES256_GCM,data:Qdr7A6Us/dF2mD0=,iv:FBKt8tKSGYVvtlXij4nwJTinfvR8xweUSw31ZDjacm4=,tag:Te/Af/h1wSTigHJdceMdlQ==,type:str]
nextDnsServer2: ENC[AES256_GCM,data:kRGXIdYn4/QI+KM=,iv:Jb/NiswS7/lX9Eos544h7prycewXbmA+z3aPNDz8bTI=,tag:dhUEsx6RTKzj5c/NQ6XNWQ==,type:str]
nextDnsServers:
    - ENC[AES256_GCM,data:wx4GUG8Y6X9Z6Yc=,iv:j6DRl/8kKkk1cH73bzCKGEbsdGMgutBuKHR9j7hdPYM=,tag:PfUVpl1z5Q4W/EqLIBSYFg==,type:str]
    - ENC[AES256_GCM,data:+4L8bIS8XbjBf1Y=,iv:rWnq/NRHqONTuCFyZ6e0M7pfmViaWCOYe2Xyt/mTwT0=,tag:O2J5Lmja/ksbGf4WdxoERw==,type:str]
nextDnsProfileAsus: ENC[AES256_GCM,data:Kew6fULW,iv:cehYgZysSv+3R7W1iX46XLC9IDzEnweOdD5yO7sxuHw=,tag:XWapDZnycurws3AxYmqmEA==,type:str]
nextDnsProfileAir: ENC[AES256_GCM,data:R+0OeWUp,iv:Tzs7uvRdw7dtpMvh310/n8paQzIJd5pXpfZ8qABQZhI=,tag:UZ3ar4uI+Kw0mhGtjV3vLA==,type:str]
nextDnsProfilePro: ENC[AES256_GCM,data:8DlaikVt,iv:SFpD4JH4Gsig+fU71sPV2L1vatAOnsj0RtJZBbAix/Q=,tag:xKKaRe1zspdMMkP4711nsA==,type:str]
nextDnsProfilePhone: ENC[AES256_GCM,data:8CsgsABt,iv:FCvUZv0EH990cIY0n3BwligqurcnYm3dSjmiXiODNv0=,tag:Uj7tawPcadZ0+j89Ln3N2w==,type:str]
netdataCloudToken: ENC[AES256_GCM,data:zY9JyTFCsfiIT+dvkSqHr7gJa6sLejT4XiPzC6k15iPE5qMqFvoq0k2vdQL8nfHA0JLc/kWFF02WzZK7mGy5DKIg1tg8xtcs9Sbh6PA6mPMon5omyyn2olBV6R3TrLIxqw0A5fYXrMtrCF0dKmJbMHh11hX0Q19t+SBCW/InqH847nU6Pmcn,iv:ufs2lUlTF+ic+cBDuqzDuOD6x9IDDN7McdE6K5EfXn0=,tag:NJ3sbzxlIY+Co3pxMT/dKA==,type:str]
cloudflareApiToken: ENC[AES256_GCM,data:cGCOMMxTZTKJv8+1L0ctWCvuegWJzFFxWAANzvWWBqM1wc/0ejCKjw==,iv:nz67kFQ2CwJVxqPJzwIk5VnePMxulfYJvPvlEvA29Os=,tag:MR4gYyn+P9xRC4hH0RpX0Q==,type:str]
anthropicApiKey: ENC[AES256_GCM,data:UeHtP0hk1VV9MG/HooO6p7RGNUJoTTl+7Kx3DlEg+avAJSBNoVxvO1lcp0RvN4hsPhqY56o+lfuis9Lm2d40pKQYlZTcN1ZeZLhodBCNQKP9VEROIAn73uWhLJCrVDCuJtL8EkPimjWU6Y08,iv:ySalk+uALSs3lhB7JNgqruOrsf8Jza9oBF1/PqiU+Bs=,tag:VfRZiidmMk0vddfQTN6PmQ==,type:str]
openaiApiKey: ENC[AES256_GCM,data:XIZoM1Sqf3D1+5J6exaOJkTqeo6qFXzh0wFhB04AZfpZkGiq5rJKF5CTbiY7mKzZvrRA,iv:sOIsJFbisxXwfMrv4Zn3V9qH/GvP1zVxQ90PmSXqQnI=,tag:k1rdos5PjdkubUNv/q04vg==,type:str]
googleCloudProject: ENC[AES256_GCM,data:c7blEBG8xIYwFVm4LhFzKEuDcl4/HA==,iv:km9OIl7+8R0gvxXipQRsvGhzCOaAr2vJ9zDDUIWuY+Y=,tag:NL6O628oR3ur9UIOW9xmKQ==,type:str]
githubToken: ENC[AES256_GCM,data:/hK3aC/IhK9g08tPcoWNyuxI1bAdiBlYjuBj0d33YCdwldyEYvJw5g==,iv:zWuJCS6fRbLdJR9ulE3IWVi3KlkIZ7QO3Z4rVwwEvK8=,tag:c4QD45le43s6PT3/bhq5DQ==,type:str]
ghMcpToken: ENC[AES256_GCM,data:VZc+sve92mmvDglxvnrmgSBec5NUlitEqeVpELOOe8haeRX7CD6rzA==,iv:uBv6Hf4Rw7y66xftqBDSFY4zkYWhZVJGZfbywMiwcTM=,tag:FgtxhPQ7ei64zYRUwPNQbA==,type:str]
perplexityApiToken: ENC[AES256_GCM,data:Hqlg8wsdmnIjNU1FaqRh+Ieab0iFVDxCo9BYAQ8A7xUhkOt+fL5wD9oHbpXnLXxZEaNwNQg=,iv:eInjGNhEUMVn1nhQ1a0UBFoHdP/vrhxH3AzeVPAhU1c=,tag:i7XYOlRBIChFAW+R5z1CXA==,type:str]
discordWebHook: ENC[AES256_GCM,data:mGMwETXvUtaLl4LZ5nC/F9JoTgeewWMQpSn3fkkffDyot65sOaAICidxfA8GKmy/tOF+S2EBcPM826WPB4Qz1saycigHJE3L1YKIdal9jWE/UpCq1xsQ3E+LXbjUS7gm89tkkcMcoiyil341nupg+sd4Bk2XUtLtiQ==,iv:0YYQFpVA+wVoCusJBGJLlYQXO9bOk5FLGBAgS2xPmnI=,tag:BMcio5eEI3oMcigAFESN+w==,type:str]
longitude: ENC[AES256_GCM,data:27PZeh5mnw==,iv:U1WMo+ML6E6/EUvKL6DueuN3V3mzYXw6cgdcZ7gsGfM=,tag:wtIxn2O0QWuksb84bywTrQ==,type:str]
latitude: ENC[AES256_GCM,data:fjDJjFadAw==,iv:UfBjZhvuYtNMMMU7tDjmne5rpE+ofRdcCbnVyVtToDQ=,tag:zvEeEU19Q6gEjQPKFlUGeg==,type:str]
time_zone: ENC[AES256_GCM,data:hcdb8LmOq3HTDJ8=,iv:eIMRWVz9YICPiQm4QMZkqy2WO+1YDlKpFd+r9diqQAs=,tag:oll8VaejW7Jec9VdaGCGZQ==,type:str]
timeZone: ENC[AES256_GCM,data:eXwkCEPF0HrtyBA=,iv:o36uJgSiYhO+MTXbPobusPjFBfi6YyNN44PDkWdhRts=,tag:Ur8JXuN40VD2ELpG0kN87Q==,type:str]
externalDomain: ENC[AES256_GCM,data:Faeojb2LXeh6NJxEdQ==,iv:AbjAFjWJM3AVvakOA4qb4S50qxjSj+DpDQpsHbksYOY=,tag:V2x20/cOrHWcmt7zBrhTow==,type:str]
transmission:
    username: ENC[AES256_GCM,data:w2vuetmY1qrlFcRNCuA=,iv:vRnUIjpGK5G7GZX+EGU70Smt8j6kUJYErr8/aOrXx9c=,tag:dC573Vvzpg/FojRXaf97yA==,type:str]
    password: ENC[AES256_GCM,data:WEIJhpF8L3/w63Rt8l8Rqkxi02g=,iv:9W+hDlpWZwEO9L/cWlHllWH0RkccEFPuseTR2uRg2pw=,tag:k7nqfbKQgSJoX8A87rIeIg==,type:str]
stash:
    username: ENC[AES256_GCM,data:qkTato9C0eYM5JWbUw==,iv:jOxH88BOCjGpbD9K3hjTTroPaKm5czcg7zf6WVAh0NQ=,tag:wuk7mmId6enWixaSTOqtPg==,type:str]
    password: ENC[AES256_GCM,data:VVC7ci8SkewP+0fBa/o+dGhufW3SNSYQ4hVMGFzGmNlbe1e0aEdXFEkep7ngo6xvFh/T022EYJUDxJhE,iv:6zVk7ZBTrteu4poFJROEgcEl6tnVNp9p910LSSw+UH4=,tag:NFNjHDQs1AFnqa6Z0DtcNw==,type:str]
media:
    username: ENC[AES256_GCM,data:J1E49pAfrlKXEoXtTQ==,iv:wc+ZwAf82RmYF8QLLytPjgnF+A0v+NFu/IkXA0RRvuw=,tag:dRk8zwlaJ4wQ4jCTCTsCCg==,type:str]
    password: ENC[AES256_GCM,data:ac9dy/LQbatSuE+8sTDVmQkvhZt5tlYgTUDAkeDAFlAgM3r0yT2f7TEW3KJKbECjCsFPc+bv06pt3uWe,iv:L62dwTG+qNhClm2E2VdkrrRPTA2zWgxWK96OEofU4AA=,tag:sLQzeO5L9dptgaa8Zsh6tA==,type:str]
syncthing:
    credentials:
        username: ENC[AES256_GCM,data:Q0kmyZL0ehfR0P8I,iv:Sh5XvTU2XpQAN9IvubM05sTBP8iT+xj9nd/2lcka9hg=,tag:24o6iHNFz+PGDyXTILnHVQ==,type:str]
        hashedPassword: ENC[AES256_GCM,data:hxCdo2RAsS1v/5Tq5BP35dK74nwZLGnCaM3Y06b9Ad243K6sTuMk0sAjC/S/fA7wUOyt2k22PtBtX5yL,iv:0Blp/RM0DD8d8gVkToCLXV/ZdsmCba+1B7YxNAM9opQ=,tag:cyRfbg4yUmaHxR1vOnGHNw==,type:str]
    apiKeys:
        IvansMacBookPro: ENC[AES256_GCM,data:VPU0FRKY11ZN5we4vwvMYFuTM6Ic0jOL+72/Iax+Fj8=,iv:33ieMTxLnp4qnEDGBNkEHwDUDi2JpVkRxPaMV0jD5Os=,tag:lJsOg8FHxQqLdQHki5BxhA==,type:str]
    devices: ENC[AES256_GCM,data:3ZPsVaeTWKIesxA+vGiJ9ClcNlqJuZ54U/4l4yrEEKK43YbE0LrrrABRnLtYZl258iai8sf06POo9FBsQD1XM/WT8WchNq1hojn7sVhmMiNttLmEARZUbi5dITJwZ7omsAmFjFOdfQW4EIeWkJh4BB5OVhf/oy6UzMzOjzHrRV1BVGeLUb1wHacJzE+2xW66sCzCC85CzI2umaQSUdc1VtEYwoLTQkmncdN0mQHy6gj6QrtipYkp3UiydzV26xse3xCcjfc/6CGKxLvcGjfeptpWOUKWdVAOx0+hhYUL/CafLDvy7zt+UaoFYah3dVTFuD+Hlrb7l79r4xfe2PhNvTqJJXVz8s1EQw+L9HeHIZAxCMO9MJu+j7lhS+UJ3pYhBb5K/qtFriNYIwEigJKCOd3qmFfb5SRJcnZPT4XNIaVVIS6Lkx4P54Ze/dvpjUI76tPWqil5KDB5l4zBoU+3tRPfGsj6CC6qc96sX90KvkwN2kFAS3KntrYr1ElcxBdTymiNyh3s2ja7k8HF4U7Xe40/0x7suMzbVJYcL7zj7ZsTIpxwwkgJc6Xbr9o+t2wVNnPnIxdhIaErOoyNgejhyqEhiTPwS2fHO0FH2oJX5aZejgXNmw0xoVlUv97XSSK822bg6Y0ms+mq96go9sO6g9mhBA/utG6NtaKbwpm5AvVwwsDVD4r70Di1jYHG2HUAijLEn2+tsFyDWuHZgbES1UKaSs40sFt52GNd0AvmKPf2hfd3FwRJjZAJmOD+nn8jdBoNT+vRiZVEjcyPXC1Y+fzjqQ==,iv:5XBJhtJ5yv246sMKaf1wJSen68D05CkmNNYFFmaEXDo=,tag:jc0IUQMgv9epFXM20rcZgQ==,type:str]
bitwardenSession: ENC[AES256_GCM,data:jcuP9/3RCVpXZo5qInw2IfjEn7CiLApEiruRI5iUPX2zdz+Ef/BeV18B8ZTSJAM/lmIiDgW0B5ut/Rn90kRkOLhAEcOIzTBmPiVfuLWhOU6anFbEo7YR4g==,iv:WXSpGr36PUanZIWKEw0o3pAMBA6me7RZkoMfjXuf7so=,tag:r35ePrZBCo7C3sLl/1xzMQ==,type:str]
telegram:
    apiId: ENC[AES256_GCM,data:AXuN3UnSO3k=,iv:U12ytikWe6aAZLSU+i3fkE+D+yD2Ey0sGkoe12caWq0=,tag:kD45nne1XqIv55w9xxsjlQ==,type:str]
    apiHash: ENC[AES256_GCM,data:IN0lNl7Gv3uLgYtkNchLIWggUT/hrmqGevkKF5uLDK8=,iv:JluLZ4wzxHXfSWPzHVqFZ5ZWv2k9FSzxl9awWAxfkD8=,tag:/u2bIqIF3ImwKO92n29H9g==,type:str]
matrix:
    username: ENC[AES256_GCM,data:fNtsXO45We3Op+uLbVW6,iv:5lxjlF74nLuiJ3qizX/4xCNuFBWPuejWFBey40lTsto=,tag:E4DyXyLoTpkUY3+DVeYl7w==,type:str]
beszel:
    hubPublicKey: ENC[AES256_GCM,data:XBtn4Tzxm07yN2SDK/zLdutjO2vMTs114q4OICTkLYmQUL6KhONSJaUPnyAKlHhpILney4GBRailXP9RsLq1Ol4A2Afev8tqRFS2Pzf45HI=,iv:ulpz8qh2fqzuypfRAO543sbybS9mTBMzytaFQWSSXKk=,tag:5TdNHU4EvbymohEf761VwA==,type:str]
    email: ENC[AES256_GCM,data:lQRLD/gwpmc00Husj0SNIo5FBFw=,iv:ZybmbZGSs5rlN2DSUwyrVQfm3K8XHc+6b+iCjzh3AqU=,tag:5Xn+WE2I7hkDTuTaFMAZGA==,type:str]
    password: ENC[AES256_GCM,data:DCtYgCkWnp/lyPSyOJeoYC51jPQ=,iv:PEVfKeiDl7I4R/WvaoXN3kCDGNESITVi+mTmdMcTA4g=,tag:sXgwNbUDBwU9iD4qkBVCBg==,type:str]
audiobookshelf:
    apiToken: ENC[AES256_GCM,data:ajrXRZkPRB5dH69sTlKyTIU5vSaGQzSFqDGei8ss01yZd5j/FWSwVgkzs3pIogGZbEW0pp61eZebBCoapsLARaSn21H0Ie45fiX3QEXxrCjW8VnLq+4ibHSzS/Q36neKdRKgK9dzKa31ooxrfG24FNLVWGvo6JPWVPoT/umc8bs0izp4Zam3BMvKrZ7b6YBSQPF2VmryNs9ynAJwm1du4jMgDLZyM6YbtXwuzdzxaefkMbxu23D78su+rNCOdTuUng==,iv:Ftvg+Kfg5R608vOGj+jBLLqHVFe31nqoNLTw8fkVvWg=,tag:9JMrwvQWxOCDP/vXKuGyqg==,type:str]
    url: ENC[AES256_GCM,data:50GcY8C/FZocODUOlDPvmPwUWyeiP4aQGTKpCcR/wCLAkYCp,iv:jLwW7bDS7Wr66x8Ui/gFMlNGhVcAetcnHNbhl7H7Cls=,tag:c5oUJNoP01DnAWgulEaCHA==,type:str]
    textcastPassword: ENC[AES256_GCM,data:0dam+10MeYVU/zMI3fWym2i9/Gw=,iv:oKiXxZ+iciYmnEMtrYs2xfyB4wLbUSzVur25+GRZvxY=,tag:NkZhjDIeKLxOpCdJt6DcUg==,type:str]
jellyfin:
    apiKey: ENC[AES256_GCM,data:k6c+jTJg8OGXqy5vr0V7fWiB7+mB4QY774qpVj+Pnas=,iv:f+7s6Xr/+uV68ZQAB7k1q6cjdFtydjjfV1Xr5ZDwbIo=,tag:4Y8ySA3K8sFevoUtihF0EA==,type:str]
arr:
    radarr:
        apiKey: ENC[AES256_GCM,data:7k8alIDLKLH8KazSvFDXbrYvjKUZnr9qsKfeGdR0diY=,iv:DTYqWv8VmzX9I563mf1L20ubSv0mba/DIQbKDBg47YI=,tag:gH1L0thJzjtoqvOQYsfygQ==,type:str]
    sonarr:
        apiKey: ENC[AES256_GCM,data:8itbqHnnzOQkFsyVSykVFomy/UjjOtdC5Bsq6I40hdI=,iv:NjGQVkcBR3lfAOrcr9r9QK+tB+yPrxj0LwdsYpTpjyI=,tag:Dk+wUEz8XneQHqgm2E7wXA==,type:str]
    prowlarr:
        apiKey: ENC[AES256_GCM,data:xeA8tsWucFvfJ0YAI8RjoS8ZBxDaYgUA3TKigGfa5cM=,iv:Nfmyn+HaXM1qP28xS2gb904GhTJVwcvnoMJD5hhSe9g=,tag:6PZnSraiUGCSShENWdkV3A==,type:str]
uptimeKuma:
    username: ENC[AES256_GCM,data:dgSfFHjrnw==,iv:2CfDxHRSzk67NLhCvlu5Dc7fi72YweOAmV7OW/dQVjM=,tag:1RvqtUoQfDZpWq1VWmyemw==,type:str]
    password: ENC[AES256_GCM,data:/h+OkulDS8x6GBbP1ColRsdWJDs=,iv:FTqp/bg4KAysE3UmsvN7RwK8NIqaAJmn7ggqCB/K+10=,tag:1uKoR7ZyXGa9WWYL5NX+Dg==,type:str]
    apiKey: ENC[AES256_GCM,data:wGolRdto3GQaGXRz/x1tnEWJpLCTQWonkEa9e/m70EOzLgABP7AFZacuq9k=,iv:qMSpeLrRxDwhBzzROJscDEnqFDfw8Z4EvfZXeDC5oxk=,tag:mAYCijd9TG8IqaURPFtdsg==,type:str]
podsync:
    username: ENC[AES256_GCM,data:8BqaPRe+t67j7XAP,iv:L0oVfBBH/k/2qx6I7b77iorwsLdhvQye+jAvKF4BFLI=,tag:F2hBoYQSIgjVoVJYqZIlHg==,type:str]
    password: ENC[AES256_GCM,data:ROoK1ozjfjMGPe/NTCYrk0VM0U3xMzAvdedGJKCCHX+ZYqD2LYQjgH8Lys0JJzHsUOnyvhLxtdTBKdSq,iv:4f5rJ1giqNj0bMKQwm+lDvMiW11HpiMf3JPX3qzeXb8=,tag:skR/AdomZNJL9eDTJ/f1Bw==,type:str]
    youtubeApiKey: ENC[AES256_GCM,data:sQV9se0T/W3SSf85BvpuEghj/q6pNdfUSChGq+g8gIoPF3WuRiB9,iv:t3YUZYdpRjFtf8N03Ly6w3BTZ9KcoeckiKrONWwjgSg=,tag:9opmu+81K+BeOgCfm5vsqQ==,type:str]
    vimeoApiKey: ENC[AES256_GCM,data:hRkO2lI/rmtNpgerwxLzIa5pSYVip8gOR6u6d0tmTC8=,iv:nNrehKLaIGSME24xWgIqhmIA85B4J22/LDUO2vGljow=,tag:BhcXcyrgKlbGkf9/RrRjkA==,type:str]
postgres:
    monitoring:
        password: ENC[AES256_GCM,data:SWciGi2U8VZProVjpQ==,iv:Sfhnlt/GdFyhRUi//Phz0pV8epeLbdw3hqHI5j6AipU=,tag:btKXmUJokTkgd0Mj8eubcw==,type:str]
router:
    username: ENC[AES256_GCM,data:q/oJypGeuup2l5PBPQc=,iv:txtKvH3Gj6hBzStP2Sh+OUHyJdg2H25vrRq2D0v7hxA=,tag:FllyGv2mrW0uI/2OWyyznw==,type:str]
    password: ENC[AES256_GCM,data:ks6Tbwiy+loRRCcq87NVS3RI/S4=,iv:+y7g/9lC04LER905+5Hce84sM2s2nYKDgTgqZaxahJs=,tag:0eKWpPhKfiF9FwiIA1M03w==,type:str]
sops:
    age:
        - recipient: age1ya8kjpr8klstrfaq5xdu43t3lafe8wq2up3uhezhg9z3xaxc2ayssvsa59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOWZqeHpRTFZTeFVEaFQv
            ZXZRWitZZ2pjYS9yaldUU1pGM1lzSDFueEhNCmtrbmFHWFRDMUdyUU1kakNJSnk0
            RktRSE1pMUtZSVhJT2ZyZ0FnNFd3NWMKLS0tIDBKcUdZelNienhWbmZKMjlZTmdE
            alZaMFIrcDJma2dGK3ZvWnN6SU5WNGsKqhXUXH3DxPUIYN68+boRF9EQ6ASaEZVz
            WiWwuIBoRp6lnD3yrZ7vOIEQXnBdoAO1ddgquYxB+iQUb492aqNW9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rw5u356cck5mx4ee5hjtqlc2380ycyvctddl6l3kwfj2nkqksf4qclnx0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNnVETjBlbE85MW43aHF2
            SHdXRmRRcFlmMHN4c09tUXNXa25rSUNVQTM0CjdxYXhjUW1LSTYrN1hzc2RqQ2gr
            K0tHNEIzOGJpVVJVRHRVbDRFWHgxc0UKLS0tIHBqS0RDVVVIRloxQllTSUt4a1ZX
            S3RSeXorYkMrR283dGR2RmNqYmpPV2cK1m5K94KKR8I4563A5mG/RZl5tYQzthFw
            AOr0Ny4u/oLVFnKuomd0VUXOtvxo40x7dRsK99l00UE98PHgUfER0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nxsvvlxhutf7kr26ucc60r48lge779dducnknyr9pceej52nqgnqlvqe25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaU1VSc015a2FxS2trQ1Bh
            Q1IzWk1mcEQrRnlqWFB1ZGVlRmJnVmM0Y1dzCkVveW9tbS9mUC80N1hLVThtMDky
            OCtBYmdPWmZXTis5bkFzWko2Z1I2Z2cKLS0tIHVZZWNVZlVlYzdkUWdLbWY1cGtk
            Y0QreEtRSXd0WW9DQktudmtOaVI1TlEKwL/Vseh9W/GkNu+rOZKbm0eoVdG6w+Pu
            xsBFzFBTXdrmBg0IkwPUe584ICH+c7KMMd8poYoQ9cewUvEq/ph9og==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12fac36qxkpulhakkz2e7z8efurgn3xzqv04ceuv4vjdcfnwcl3cs3cm7h9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NWJwZ3ExL1UvOC9WVmdu
            aDN2Y3FRT1VQclVhNnRGcmRnRnNaWGpPdWlBClZoQVNLTnhRSG0xSm55cG9Wc2FR
            SlNtc2tibXJJR0FDbGJDMXJvdkdKVmMKLS0tIGJPK1NINUw5aUR5ZzFkZHBwNENv
            WW9FTWd2dUJhV293a2hiOS8wckJ4U2cKAJv038RB8G69tBZ+WQ8DKVyDTNZgmq5U
            JxFwpoJTOHggZJARBk9CQVnL9mXNDHhVonkE1/4fEgwlYRhKsnwvCg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sxcheqlg4ztsu6ly3mfzmx7a2s7ht4znkez7q0g2rcmwr92tjfqqf29plr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3KzlXZzRwUnY0T2dyMDda
            YlZ2R2FFUi95aEEybG5VWHZ1OUpsa1hHckhjCjczdXc3dEYwQjRHU3NFSUpZV0hC
            V1JXakVCeTAvSnVOcnRtRWNHNGY5M3MKLS0tIEZ2LzZteDBaUEp4Rk9xUEdDWEpn
            d0JGSDRocEVFQ0tHRm9MVUU5NFNwNGsKHqaYxi08B7zCxt0us+1EoHFrAH3xmtLj
            xd3ZnzRWpiEG2tTNYoJuUwumItG9JLvb3lVosUvQU4bVITZHNPrB9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13gw88tu64vjr0gmy442yaf7c6zd3ph96epqktr8ka4v5zea494mq9whmjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS3BMcVJoVHBDazh0dkZE
            V2M5WTd5ZFMySVlIN3gxRVN4NUZpbGtSNHpvCktMK1U5c2xMUkU1M1VXWkQ0c1k4
            ZTZPSVpsWUpObkdaYzFvbXNFZGdhNzgKLS0tIE41Wi91emdMK3QxdldPNVBVbjlh
            TWREQ1MrcTY4d3o5R01vNjJCMjRLNk0KiiEAb31OVCxdm9UlTXlFV9yy1lLg8dNK
            TIb5IyTaRfWVPVDoJvgov+lp1VPEW9cVr0mmYeuJwoJ5kIhwz/ER7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d8zecgxstqurz80ecn0x55neucxss7dgpm63pkspzae7wtud5qtse0xcqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVkg5anYyNGJCVzNRZE1G
            YkpxUFBaZlFVUE8wT0pvT1d6Y053OTh4em13CnB5QVg2MlV5ZDBTYllPaCtKQmt5
            VUxCWHlVZmdvQ1FMbStPU21qZUUrazQKLS0tIGxpRlMzRnVjb2RSTmx5dzR6TUN6
            OCtGNGpUdFM3c0ZUSG9aV3BHWVM1RjAKWe/w4cS2BsxPM28qzB5kfpAcv4Mj3jLn
            MsJ9qRLZ0ye6eaaqGZMGTKsY4sTKAVHE77Q5PlHqNARf/uozDBZ//Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rgdpf0u4mfpe74xwecknex6u3lcdpxm8jfydu4n8ftk4yjsngpdqp5rqa2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cmRZNXNNai8xY045aG5u
            cFJjN2JsQlpGWTdSOENxT2FKdWtMek0zSG5RCkoxZDdvS3hPZ2p6ZHF3YWJySTcv
            VU8vV2UwV01oY2FOS3gxOXdvVUhXVXMKLS0tIGtYeXFub2FFOTE3QXBmS3ViUmYz
            dUFqTG42YzVlODhZcHZnODdRVHpUTjQKZVRNAGiGcnMv/z7KnVSlWpx03a7CVv7Y
            9WiFEQp+7WCaG8U94q7dem1KVGFatG37S9FeIOsQ2Sb5xtdt11Y8Lg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1grre437d8vhr7wlq2h05mtn8ufxddwdktzv6aw60qyuqgy87t4ps0f2tgs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcVhJMlNCTDVlMTdHeU4z
            Vkg0VGxKS2ljZGtOYUQ2b1lTVXE1YzVPUmdRCnN3dU14MkR6UzFtUVJwc09mQlh1
            aWgwK2FuSis5TUlaZ0ZwSS8zSkM4RlEKLS0tIDJjL1I1cEhzSmFBMm9qWUdqNURT
            SzNhZUE5S0xtcGNrUENHaFJGRmtJWVEKAwHEANulK/tb2w6p7scBQFDPMJ//Pvd/
            gD9r1ploJUNk1dLCn3iYv1Jm9Bgpf9raPlY6gxDl4zuUyYCMp9zxqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x42q97xw3synk305twvsxkslld2205h97t8d9z8hy8vl8hzcpgas6d48rh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOWdZMGQzU3NUOUlGdTRl
            ZVJpb2VLVTNEaFJXTTU1d3NMTyszTVFiVjNvCitubXplVjhZOHVVUkR4b2k1cDBq
            OWtWRGcvT3JVRUxQcUM1SW56OUtLOTQKLS0tIGdWV0NMTG0zKzdONWxZNHJBYVRU
            N3VKYXd4aXhPZGVWUlV5bUh2Y1h6RkUKT+rNIArEe56wwsFwMR7r8KQpMAm3SB+U
            cc1iNIVPmGurwQSOmP7qEJKcpOA1K7vOFXd3odVht8ob2ixO1nMz0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13sfhwx56gvfzprjzg2guzf5l27jsk5szu2n54tfc80q7s84w8etsfw550z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVjA1ckNzeHZyTW04clh5
            Uys1ZW5kM3dvekx1NFJuOG9yR0E4YXhmRG5zCitFMDJpOFRLK25nOFZ6TWg5S2lP
            UWlZeHNmNXFRRzBkWG9XVVZkbHRyOEUKLS0tIFk1QU02UFdyZ1Rod2xBYXNpd2FQ
            YzRNNmFERFZ2anFNZEJacS82eVo4d28KfKetX19ulFF9n4i1wPkupMy6DnVSv43V
            oXVqIJLwwravbSDZSaZuuymTIvSLf1QUpkXtkQuQnabAlDE6uHo+Sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13qs0kqn9gnyuv30xehzls8cvshs372j0g02lthfvn36s53erp4tsy2n854
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSUltcTJDWnBHdStNbkIr
            U1hSbExLKzl0WTl4Q2VMd28rUWYydUtvS0JvClZrUTlOSnM2bEtvK2liNG80czcy
            REZnZkxYczBYcnJXME9nRitJcTd2OGsKLS0tIFpPV0dxVXJ3L0FvVEZJTmdXQTBj
            Tm8yZGdjT2hFZTdYL093UTlhY0ZiKzQK8pzpIBeclYlTHTLO8CWAMukIdYQDsNUN
            iT8l2AGng5OQNAnK5elGseeuWAipn6lac7U89VyxQfEuap/8CJbKxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T19:02:19Z"
    mac: ENC[AES256_GCM,data:e6pgkmY7hajE3OxnT5Hq7THqJ20fU95GW54f+Z5tmuJJmtOPME+w57uhYQmA1v3kw9XGeQ7/7ZazIg/1FD1sTbDfMzbfX/6Rgfc7YcQZwRTBTg+a0XDbnsL4goWQHEve2YRCYDn0vL0ZiiFGFsPIP/QBU/N/ufwXCGlVfZuhq2c=,iv:tl4DdhhT4R2VWQTY+GP8h7xl/tX3AkmqOy7OFyzfHKA=,tag:7VfHF8a1OABTctT1ECzHkA==,type:str]
    pgp:
        - created_at: "2025-12-13T13:36:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4ARsG/9MZa0AQ//d+VTOwZ1ZByEpz+7H554GLVBTGAtOLKpdfRMqkbtOXrx
            JPuZfT6iMSQ+1gb2BphlgYjmZZTticT73iPGWQ/l33F8MO7Zgg8mrzJVF9zR0gN3
            3a7JfzCoBlk+CpDL8jDTXn3AIZicaybs2IjlwLBj5oYRjAodQFDcI0ZShnHEH1rT
            P4AZiSeFYYzzh/V0UyBLeyOHNTPEo95P5XPqVcN899MwvwuGSKxWt8xzBk4Oi+bP
            55qzpKzUDQ6TWtCULezeh6DuPq5RnhGOjX0+5c8d756gsHRosNLUJThHR1iecfBn
            JIzv3SHPUo00tJEX9vnDc97rI4941Jz2ywuLrw/g5CaS1jsW2Z3hrJgV1ubwEwae
            2C6pUMgjDI0h+p9Mq3EAHMKFfd4on5L1B87L24+YrCCPJ41Qz5x0tSOBMWIOlmZP
            n6SgiU2CsKpVzHJ7OpN9A+QKWhkJ1jVXuFvkdfj/BHFOsxK6ppu1a+rh6NTp3RgG
            tlRVf9Db1f6c+zxDQnkMKye0fMaiXt22HpKxzdcbjY4ApQbg/JeokG6LjUyQq77p
            6FxKHUN+kUI94kqDS99N2yVojYBmRxilEX/rBElPa/SzVA69937VIoOkh1bDwVyn
            3+xdCGb9hSR9RRjfFJ+FaN9B30p/ybgyvx13gUY2YrFP3TLKNTa+tMc6BFgnkJXS
            UQGzfH01rhCthq9SHIhoxc3VV/QheCn/nY/rxL3fSeNvM+B2MTMFt8LYMNFTshrR
            oh9KPuTNr3+YAvxFB9o8P9zGDFy/oSWM3arggaOLa+iv8A==
            =dILb
            -----END PGP MESSAGE-----
          fp: 6BD3724830BD941E9180C1A33A33FA4C82ED674F
    unencrypted_suffix: _unencrypted
    version: 3.11.0
