email: ENC[AES256_GCM,data:/lZwlnfVzI+IGDxgKr2E6CrxliQBUanZ,iv:fuSEAGB4W45FTvEx7U9UXn84msJ9qK0ULkTCmZ6ZKz4=,tag:O2gKK09pPMF8sCEQGh8/yg==,type:str]
letsEncryptEmail: ENC[AES256_GCM,data:nW7oVaB3U8pzUlwDdUyi7OgiuT0VNuZECC8=,iv:f+oIBOjYAseHNgPPGRqUeRIiqb2MIxrEBc5MO9zyIeY=,tag:f3EKXUDLT1ie7D4uBE7Ryw==,type:str]
nextDNSID: ENC[AES256_GCM,data:6Czx4n8B,iv:9zcLyECUGcCC8sgEhxOcTJgDWvOK5YLkvGyBz387N/Q=,tag:GlOhWhBBN5dqCw8ykF2gEA==,type:str]
nextDnsApiKey: ENC[AES256_GCM,data:d4giHjpi3cdQyMvWvcmdQhnEGad7WEI/jJ3SM2a3fmbOuqZaj2ehPw==,iv:mt88X249LAdYFXwgXvNDe86+4LNfib635I0lKHmruSg=,tag:UqjKp5ic0Szcuk7Tt/5MUg==,type:str]
nextDnsServer1: ENC[AES256_GCM,data:Qdr7A6Us/dF2mD0=,iv:FBKt8tKSGYVvtlXij4nwJTinfvR8xweUSw31ZDjacm4=,tag:Te/Af/h1wSTigHJdceMdlQ==,type:str]
nextDnsServer2: ENC[AES256_GCM,data:kRGXIdYn4/QI+KM=,iv:Jb/NiswS7/lX9Eos544h7prycewXbmA+z3aPNDz8bTI=,tag:dhUEsx6RTKzj5c/NQ6XNWQ==,type:str]
nextDnsServers:
    - ENC[AES256_GCM,data:wx4GUG8Y6X9Z6Yc=,iv:j6DRl/8kKkk1cH73bzCKGEbsdGMgutBuKHR9j7hdPYM=,tag:PfUVpl1z5Q4W/EqLIBSYFg==,type:str]
    - ENC[AES256_GCM,data:+4L8bIS8XbjBf1Y=,iv:rWnq/NRHqONTuCFyZ6e0M7pfmViaWCOYe2Xyt/mTwT0=,tag:O2J5Lmja/ksbGf4WdxoERw==,type:str]
nextDnsServerMini1: ENC[AES256_GCM,data:Cs6uKglqv+PAJjiU,iv:b/kHk6RdyGIO7IctdaU5aYww21P41DRzBRauLXyA0/4=,tag:x92jmgwK7TGA+pCjOuwpzA==,type:str]
nextDnsServerMini2: ENC[AES256_GCM,data:VDOmyo4itu3EqYyd,iv:fHmirc63oa/goZv69gHcou+TA1uYNmBlDSuthwzzfjU=,tag:5OPeeIQ8rsLwY0gi/odgbQ==,type:str]
nextDnsServersMini:
    - ENC[AES256_GCM,data:5Ty8UV4jeHB6faYy,iv:c+p0sUQtOP7gbs1yLXZIfVjfeaZ0w51oCNdpqL2qj7g=,tag:YIoDRnce8nzYi1XDMzKCVw==,type:str]
    - ENC[AES256_GCM,data:lq027PhQ1xvjRFlj,iv:zlKXjk94Iq/yB4GRVbPNQLpqGAujbDYhbJ706MPz9cQ=,tag:em50fzTczv3mEy68Mb1gjQ==,type:str]
nextDnsEndpoint: ENC[AES256_GCM,data:nHBSF08hyDH9rma6DPwP67118yxB5jEmyw==,iv:z5ZCHnvHeljt/XuqzroYU1Bc1+phK+++CZWYHA4EAHo=,tag:COV/h7tLj1FBFtEqKjPI4w==,type:str]
nextDnsEndpointMini: ENC[AES256_GCM,data:lNMvjY8G3TiKHp67aqN5BDjJ75HrqFppbko=,iv:8bAiLpsKxkIT6IdbuZirp6lrS9p4NRu+B+vOmS1kmlw=,tag:UOsyCGxvkipF3q5p0Y6tiw==,type:str]
nextDnsProfileBee: ENC[AES256_GCM,data:0kOb5ey6,iv:gVuXqC+BSTzNK8JCePJI69MHOQvHk9ppVHfVX0Oxb2I=,tag:Z9TP5BoVIhrzVKgYzBxwbQ==,type:str]
nextDnsProfileMini: ENC[AES256_GCM,data:jqlD2yGw,iv:DeNoOYMJOdnZiDrIVDVQi7jFaA8pqpy7hz8ixNnGgjk=,tag:kq01UHPb/g+VBwr2O79QeQ==,type:str]
nextDnsProfileRouter: ENC[AES256_GCM,data:ib3zxfUx,iv:BXNfvxYlWqPD15StYxSQ4eeNJm0G5PcvdQnia9oNip0=,tag:rdnZYPHbCd1ANhq9c2ugQw==,type:str]
netdataCloudToken: ENC[AES256_GCM,data:zY9JyTFCsfiIT+dvkSqHr7gJa6sLejT4XiPzC6k15iPE5qMqFvoq0k2vdQL8nfHA0JLc/kWFF02WzZK7mGy5DKIg1tg8xtcs9Sbh6PA6mPMon5omyyn2olBV6R3TrLIxqw0A5fYXrMtrCF0dKmJbMHh11hX0Q19t+SBCW/InqH847nU6Pmcn,iv:ufs2lUlTF+ic+cBDuqzDuOD6x9IDDN7McdE6K5EfXn0=,tag:NJ3sbzxlIY+Co3pxMT/dKA==,type:str]
cloudflareApiToken: ENC[AES256_GCM,data:cGCOMMxTZTKJv8+1L0ctWCvuegWJzFFxWAANzvWWBqM1wc/0ejCKjw==,iv:nz67kFQ2CwJVxqPJzwIk5VnePMxulfYJvPvlEvA29Os=,tag:MR4gYyn+P9xRC4hH0RpX0Q==,type:str]
anthropicApiKey: ENC[AES256_GCM,data:UeHtP0hk1VV9MG/HooO6p7RGNUJoTTl+7Kx3DlEg+avAJSBNoVxvO1lcp0RvN4hsPhqY56o+lfuis9Lm2d40pKQYlZTcN1ZeZLhodBCNQKP9VEROIAn73uWhLJCrVDCuJtL8EkPimjWU6Y08,iv:ySalk+uALSs3lhB7JNgqruOrsf8Jza9oBF1/PqiU+Bs=,tag:VfRZiidmMk0vddfQTN6PmQ==,type:str]
openaiApiKey: ENC[AES256_GCM,data:XIZoM1Sqf3D1+5J6exaOJkTqeo6qFXzh0wFhB04AZfpZkGiq5rJKF5CTbiY7mKzZvrRA,iv:sOIsJFbisxXwfMrv4Zn3V9qH/GvP1zVxQ90PmSXqQnI=,tag:k1rdos5PjdkubUNv/q04vg==,type:str]
googleCloudProject: ENC[AES256_GCM,data:c7blEBG8xIYwFVm4LhFzKEuDcl4/HA==,iv:km9OIl7+8R0gvxXipQRsvGhzCOaAr2vJ9zDDUIWuY+Y=,tag:NL6O628oR3ur9UIOW9xmKQ==,type:str]
githubToken: ENC[AES256_GCM,data:/hK3aC/IhK9g08tPcoWNyuxI1bAdiBlYjuBj0d33YCdwldyEYvJw5g==,iv:zWuJCS6fRbLdJR9ulE3IWVi3KlkIZ7QO3Z4rVwwEvK8=,tag:c4QD45le43s6PT3/bhq5DQ==,type:str]
ghMcpToken: ENC[AES256_GCM,data:VZc+sve92mmvDglxvnrmgSBec5NUlitEqeVpELOOe8haeRX7CD6rzA==,iv:uBv6Hf4Rw7y66xftqBDSFY4zkYWhZVJGZfbywMiwcTM=,tag:FgtxhPQ7ei64zYRUwPNQbA==,type:str]
perplexityApiToken: ENC[AES256_GCM,data:Hqlg8wsdmnIjNU1FaqRh+Ieab0iFVDxCo9BYAQ8A7xUhkOt+fL5wD9oHbpXnLXxZEaNwNQg=,iv:eInjGNhEUMVn1nhQ1a0UBFoHdP/vrhxH3AzeVPAhU1c=,tag:i7XYOlRBIChFAW+R5z1CXA==,type:str]
discordWebHook: ENC[AES256_GCM,data:mGMwETXvUtaLl4LZ5nC/F9JoTgeewWMQpSn3fkkffDyot65sOaAICidxfA8GKmy/tOF+S2EBcPM826WPB4Qz1saycigHJE3L1YKIdal9jWE/UpCq1xsQ3E+LXbjUS7gm89tkkcMcoiyil341nupg+sd4Bk2XUtLtiQ==,iv:0YYQFpVA+wVoCusJBGJLlYQXO9bOk5FLGBAgS2xPmnI=,tag:BMcio5eEI3oMcigAFESN+w==,type:str]
longitude: ENC[AES256_GCM,data:W476HRmCiA==,iv:YQb9jJFSzyczw0GjQlEqyNenoFMG5Tod9/KmF/mSo6E=,tag:MFImft7GaGBZ6crN5k61fA==,type:float]
latitude: ENC[AES256_GCM,data:9BDdGHG4JA==,iv:X7rFqeuVfCJGOqRB/IY1URMsfPxXQ9DP7jBSKrvQROc=,tag:LHGi11MwEGzRWA5uk1OdnA==,type:float]
time_zone: ENC[AES256_GCM,data:hcdb8LmOq3HTDJ8=,iv:eIMRWVz9YICPiQm4QMZkqy2WO+1YDlKpFd+r9diqQAs=,tag:oll8VaejW7Jec9VdaGCGZQ==,type:str]
externalDomain: ENC[AES256_GCM,data:Faeojb2LXeh6NJxEdQ==,iv:AbjAFjWJM3AVvakOA4qb4S50qxjSj+DpDQpsHbksYOY=,tag:V2x20/cOrHWcmt7zBrhTow==,type:str]
transmission:
    username: ENC[AES256_GCM,data:w2vuetmY1qrlFcRNCuA=,iv:vRnUIjpGK5G7GZX+EGU70Smt8j6kUJYErr8/aOrXx9c=,tag:dC573Vvzpg/FojRXaf97yA==,type:str]
    password: ENC[AES256_GCM,data:WEIJhpF8L3/w63Rt8l8Rqkxi02g=,iv:9W+hDlpWZwEO9L/cWlHllWH0RkccEFPuseTR2uRg2pw=,tag:k7nqfbKQgSJoX8A87rIeIg==,type:str]
stash:
    username: ENC[AES256_GCM,data:qkTato9C0eYM5JWbUw==,iv:jOxH88BOCjGpbD9K3hjTTroPaKm5czcg7zf6WVAh0NQ=,tag:wuk7mmId6enWixaSTOqtPg==,type:str]
    password: ENC[AES256_GCM,data:VVC7ci8SkewP+0fBa/o+dGhufW3SNSYQ4hVMGFzGmNlbe1e0aEdXFEkep7ngo6xvFh/T022EYJUDxJhE,iv:6zVk7ZBTrteu4poFJROEgcEl6tnVNp9p910LSSw+UH4=,tag:NFNjHDQs1AFnqa6Z0DtcNw==,type:str]
    apiKey:
        mini: ENC[AES256_GCM,data:w5Z5IEskhUVnMDy8XW45RRZ4yLAEUukGTea5bg5YeHSnN5DsNwAlSXcNHs/VKz3cjH8EnJoNA67faNEwO+yWevFbY3VtggFMKLh9wOSQt0ARZ11umlWKC128NCvzyZrbgyFX4/qvqOKu2gnOHev0+ZcB++gGW+NmYBQuIk/4oq+brItCodCEbEZTJWnJpVoVeDGm/hzN8r1YBxw=,iv:+PFGh955hFT0lcuCurIrxvF7gLbHXLLWyOHfEmRFuBQ=,tag:Mgc2brKQrVddjeV3H9PSuQ==,type:str]
miniserve:
    bee:
        username: ENC[AES256_GCM,data:DeinbWAUinFkSjGuRQ==,iv:FY786xBhJdB2YPp3lKdSPADOFNaDfs6OpKTDfX1Z8Ac=,tag:6zkCuUVITbmBkKoI02Mdjw==,type:str]
        password: ENC[AES256_GCM,data:T6DmjVA0nexE27ikHzR/1wJnu/4=,iv:YH1onlSdghbBPWCuNTMwlEsvhRfecW264Vmv3mcTkSc=,tag:TA03N23bOwpvF76wP7oPlA==,type:str]
    mini:
        username: ENC[AES256_GCM,data:7QpFR6m7Gc3T+kDPX29u,iv:KLiFyQZVc03P8Xv/Jm/dFR9v26nWuWR06+Cg/WNUmdg=,tag:o+pKeNGguIWX9U3CAMWK/Q==,type:str]
        password: ENC[AES256_GCM,data:74KcsXkmOqHWq7TLqw2Wkk9NrZI=,iv:Uu82NHkOcf5s6mij6qnFgj0QygLuY0O7TyRirK81I4Y=,tag:5cGh3NVcw2olA6Znc5rp+Q==,type:str]
netdata:
    bee:
        username: ENC[AES256_GCM,data:AAlnk6x7xcHuMrUYial6,iv:uB3yRUwN1CdPr7Bdlqx5byYcpYuDauFgGAWZvH1HIOU=,tag:G7mpDkD79XsJHGQMpc8J+w==,type:str]
        password: ENC[AES256_GCM,data:rVw8Tj2+JtIxSJTqejFs3YZ1fxazU0J/gjAxpRZ1jxXptW1qbw23UIkXXYhpWCrQq2w8nW+mhgQQDk1I,iv:bLd2/5T0R9bsLoZpzHZwx3dKODAR5fIb1rglrg5gdlM=,tag:QvQU5zPyN/uNLrOAyxVatA==,type:str]
    mini:
        username: ENC[AES256_GCM,data:+Lw4quUPSEqx4e2frg==,iv:MbvULaJxEzO1WlAcon8Fuqx6ov1ENtOW2WEaTkTsIHg=,tag:bGrvW7H+heEZ5DsH7kOsYg==,type:str]
        password: ENC[AES256_GCM,data:v4hMTpdfha2J4YPU65ZeqacVjjpFhLeLGpFReZg21atFY9r/xbBjtHyltwO5jbl40rPpULqzgCDJ54dM,iv:HFqTGOKrrnkIrzQ4Tnu4k9anf/L2Ef69ySMMgttxnbk=,tag:T+gsGUXMA12rh7K/b0dL2A==,type:str]
zigbee:
    username: ENC[AES256_GCM,data:/y3i9KX0p94i4S6Ig30=,iv:er6k8uFG0ldHAfOdpIEpMado7d+riSOFxxnsqaGkwoM=,tag:vgbauy4U7KVEdMvROCQX/w==,type:str]
    password: ENC[AES256_GCM,data:wByHrIJj9yTybGaxFJc6vefVm9lV/59/nEvpStwPRC1B22U7g67Z7JI+OthbK5eyMrAzF0OpyVhI1tYk,iv:lTlzUS0qpJ8t/UVc33qo6SAR280cJX9qPLcau59VSZA=,tag:ZDw6r+lrVSDLNwxVXZuc6Q==,type:str]
syncthing:
    credentials:
        username: ENC[AES256_GCM,data:Q0kmyZL0ehfR0P8I,iv:Sh5XvTU2XpQAN9IvubM05sTBP8iT+xj9nd/2lcka9hg=,tag:24o6iHNFz+PGDyXTILnHVQ==,type:str]
        hashedPassword: ENC[AES256_GCM,data:hxCdo2RAsS1v/5Tq5BP35dK74nwZLGnCaM3Y06b9Ad243K6sTuMk0sAjC/S/fA7wUOyt2k22PtBtX5yL,iv:0Blp/RM0DD8d8gVkToCLXV/ZdsmCba+1B7YxNAM9opQ=,tag:cyRfbg4yUmaHxR1vOnGHNw==,type:str]
    apiKeys:
        IvansMacBookPro: ENC[AES256_GCM,data:VPU0FRKY11ZN5we4vwvMYFuTM6Ic0jOL+72/Iax+Fj8=,iv:33ieMTxLnp4qnEDGBNkEHwDUDi2JpVkRxPaMV0jD5Os=,tag:lJsOg8FHxQqLdQHki5BxhA==,type:str]
    devices:
        IvansMacMini: ENC[AES256_GCM,data:UdoBqq3d8druzaz5mkz8dLpf5x3me4KuK86jCXxQO2KxvEhhennhxbXbTX+ZEcjMgFe7RRfO42I7C5LRVv1W,iv:bMkLQbfHgSp47fmMGySMzYFo40BsXWie7ielpfredLI=,tag:7P/mLrVS8ILwMDoBiuJeeQ==,type:str]
        IvansMacBookAir: ENC[AES256_GCM,data:mTRWfbj/sPg9Ec9k3/a7T6D4hPY8a+saAXG5pLGjbwKTn5VibF5A3IBJdT/lACyLcy48Vi+KihRY/oJb/EY6,iv:3C6zxlozXHhsO7jjeeQHiaGZrUhKoWDgT3Fo+ceM7Z0=,tag:Lu4wT54WL7JluxSHbFyBMQ==,type:str]
        IvansMacBookPro: ENC[AES256_GCM,data:gVGmTt/gpAqMuQqsb7FyXc9XF9EZY8fWzx1HAvGm68WfiGsw7UVVs5AB2mpNBlUAhmQCBqISfqKNWvP2x07R,iv:Kq+pvg/cUFwdQ+mfzWRGzIgYaIlR38T/U9A8ZoPU5M4=,tag:DAVtXIc7JuIyI87EyBHDTw==,type:str]
        LushaMacbookIvanKovnatskyi: ENC[AES256_GCM,data:PkMR0uQHyY4CcTAHXrUtE0YkM+JwC5WHRcRhhngzRsnIA9DgyK/6rugPP0GKxtgC/2lwJzxHB7eh2l/3DriK,iv:Zr0r23OvadezPDeLjz0yWBn9phfGeWkf6jOefUt6fas=,tag:jSQJJjNy+08eQbhB2w9Tww==,type:str]
        Ally: ENC[AES256_GCM,data:b5peEeAss4las2Fl1h0C3WOf4OqG8d8GHe/LeXb1CYQX4P7hQ5eGx+BRyAbFb8nF85UTtiuRVyKuEDT+/uLl,iv:7hV2hsLsD1c4+mpiNaEWirqj4aU7wfoZLmSv30cWUV8=,tag:YbBb2q3Xo9KUn6mOmbp0BA==,type:str]
        a3w: ENC[AES256_GCM,data:z5BvbffZ1f/FutyakyxAvYh5bMIy3s9p8t+wRmhqzvnViatYdi7Ps34qgPZYJjwajsqRzBItex35ny3Bnqiv,iv:NQNaLgWLrrIc4Vtcge4rExUav2z+/V/jKL2IQqn0+dI=,tag:vCGW9B9PSLkUmmjk4jdkrQ==,type:str]
smb:
    bee:
        username: ENC[AES256_GCM,data:wpkJcA==,iv:be1teyu/C/7f+wWjDHQz4Em2U61ku1UildNaxbNZj+Y=,tag:Ccbpli+kRy0w7w3sY+qpSw==,type:str]
        password: ENC[AES256_GCM,data:1Lw25DzbsUNVnCQLD8gtJoXlQm8=,iv:0wpmkeHvRYc8ZqCAL/A2Fb1t4pxmIeIBU9f+oXnw+ww=,tag:WxLppvaIwrr3rSdFcHtV5A==,type:str]
        domain: ENC[AES256_GCM,data:ZFaUpswx0y9+,iv:RJSnKFJFuPQBtzqXqUab9VZDCN2T+fzA6ZFKb4zMwR0=,tag:LHMQQA0z63QlxSBcw7Yk4Q==,type:str]
    mini:
        username: ENC[AES256_GCM,data:CtfWr/s=,iv:cDAfvAEmfy+XQV3NCR2mE4HaJigD2Dhk8CEsHPTIW3w=,tag:yp1Edu/XDz+yS+ygSfyKCQ==,type:str]
        password: ENC[AES256_GCM,data:Nff+QdpAr+aQyMP6lOzAQ2buv5Y=,iv:Fhw4rdB2QAQaU13dZC9iwYUD7r2HFcJaEYGC0DMqY1I=,tag:DwB+ErWWOZWhe/3WSQiXTA==,type:str]
bitwardenSession: ENC[AES256_GCM,data:jcuP9/3RCVpXZo5qInw2IfjEn7CiLApEiruRI5iUPX2zdz+Ef/BeV18B8ZTSJAM/lmIiDgW0B5ut/Rn90kRkOLhAEcOIzTBmPiVfuLWhOU6anFbEo7YR4g==,iv:WXSpGr36PUanZIWKEw0o3pAMBA6me7RZkoMfjXuf7so=,tag:r35ePrZBCo7C3sLl/1xzMQ==,type:str]
telegram:
    apiId: ENC[AES256_GCM,data:AXuN3UnSO3k=,iv:U12ytikWe6aAZLSU+i3fkE+D+yD2Ey0sGkoe12caWq0=,tag:kD45nne1XqIv55w9xxsjlQ==,type:str]
    apiHash: ENC[AES256_GCM,data:IN0lNl7Gv3uLgYtkNchLIWggUT/hrmqGevkKF5uLDK8=,iv:JluLZ4wzxHXfSWPzHVqFZ5ZWv2k9FSzxl9awWAxfkD8=,tag:/u2bIqIF3ImwKO92n29H9g==,type:str]
matrix:
    username: ENC[AES256_GCM,data:fNtsXO45We3Op+uLbVW6,iv:5lxjlF74nLuiJ3qizX/4xCNuFBWPuejWFBey40lTsto=,tag:E4DyXyLoTpkUY3+DVeYl7w==,type:str]
beszel:
    hubPublicKey: ENC[AES256_GCM,data:XBtn4Tzxm07yN2SDK/zLdutjO2vMTs114q4OICTkLYmQUL6KhONSJaUPnyAKlHhpILney4GBRailXP9RsLq1Ol4A2Afev8tqRFS2Pzf45HI=,iv:ulpz8qh2fqzuypfRAO543sbybS9mTBMzytaFQWSSXKk=,tag:5TdNHU4EvbymohEf761VwA==,type:str]
    email: ENC[AES256_GCM,data:lQRLD/gwpmc00Husj0SNIo5FBFw=,iv:ZybmbZGSs5rlN2DSUwyrVQfm3K8XHc+6b+iCjzh3AqU=,tag:5Xn+WE2I7hkDTuTaFMAZGA==,type:str]
    password: ENC[AES256_GCM,data:DCtYgCkWnp/lyPSyOJeoYC51jPQ=,iv:PEVfKeiDl7I4R/WvaoXN3kCDGNESITVi+mTmdMcTA4g=,tag:sXgwNbUDBwU9iD4qkBVCBg==,type:str]
audiobookshelf:
    apiToken: ENC[AES256_GCM,data:ajrXRZkPRB5dH69sTlKyTIU5vSaGQzSFqDGei8ss01yZd5j/FWSwVgkzs3pIogGZbEW0pp61eZebBCoapsLARaSn21H0Ie45fiX3QEXxrCjW8VnLq+4ibHSzS/Q36neKdRKgK9dzKa31ooxrfG24FNLVWGvo6JPWVPoT/umc8bs0izp4Zam3BMvKrZ7b6YBSQPF2VmryNs9ynAJwm1du4jMgDLZyM6YbtXwuzdzxaefkMbxu23D78su+rNCOdTuUng==,iv:Ftvg+Kfg5R608vOGj+jBLLqHVFe31nqoNLTw8fkVvWg=,tag:9JMrwvQWxOCDP/vXKuGyqg==,type:str]
    url: ENC[AES256_GCM,data:50GcY8C/FZocODUOlDPvmPwUWyeiP4aQGTKpCcR/wCLAkYCp,iv:jLwW7bDS7Wr66x8Ui/gFMlNGhVcAetcnHNbhl7H7Cls=,tag:c5oUJNoP01DnAWgulEaCHA==,type:str]
    textcastPassword: ENC[AES256_GCM,data:0dam+10MeYVU/zMI3fWym2i9/Gw=,iv:oKiXxZ+iciYmnEMtrYs2xfyB4wLbUSzVur25+GRZvxY=,tag:NkZhjDIeKLxOpCdJt6DcUg==,type:str]
jellyfin:
    apiKey: ENC[AES256_GCM,data:k6c+jTJg8OGXqy5vr0V7fWiB7+mB4QY774qpVj+Pnas=,iv:f+7s6Xr/+uV68ZQAB7k1q6cjdFtydjjfV1Xr5ZDwbIo=,tag:4Y8ySA3K8sFevoUtihF0EA==,type:str]
arr:
    radarr:
        apiKey: ENC[AES256_GCM,data:7k8alIDLKLH8KazSvFDXbrYvjKUZnr9qsKfeGdR0diY=,iv:DTYqWv8VmzX9I563mf1L20ubSv0mba/DIQbKDBg47YI=,tag:gH1L0thJzjtoqvOQYsfygQ==,type:str]
    sonarr:
        apiKey: ENC[AES256_GCM,data:8itbqHnnzOQkFsyVSykVFomy/UjjOtdC5Bsq6I40hdI=,iv:NjGQVkcBR3lfAOrcr9r9QK+tB+yPrxj0LwdsYpTpjyI=,tag:Dk+wUEz8XneQHqgm2E7wXA==,type:str]
    prowlarr:
        apiKey: ENC[AES256_GCM,data:xeA8tsWucFvfJ0YAI8RjoS8ZBxDaYgUA3TKigGfa5cM=,iv:Nfmyn+HaXM1qP28xS2gb904GhTJVwcvnoMJD5hhSe9g=,tag:6PZnSraiUGCSShENWdkV3A==,type:str]
arrMini:
    radarr:
        apiKey: ENC[AES256_GCM,data:Wv/1XSx44vpZ+j9JbzBPKiq6nEPH45+7se34KjRb4m4=,iv:EUs1tcC1UbDONQEGXvdzzBXx1AeCtf2kLfZWhEaJcHE=,tag:EWNT6in9q335/+JDZyP2xA==,type:str]
    sonarr:
        apiKey: ENC[AES256_GCM,data:yY4AvuDzfsGyeaFoF8EoWNdnFX+rk1m+OEFMkvcJWeo=,iv:Jt7ximrIVHhQL3uOj03T3PkcqERhJ+7EwC3jo36oslg=,tag:yOT0xZzfJVOWNY48fZzs0g==,type:str]
    prowlarr:
        apiKey: ENC[AES256_GCM,data:cfInkdSwEI64zg5s0EIBnNJiA9Y/wc0F8TTMFLy8VP4=,iv:FBUOyM//uSZFm+jcwCY8j8DbdOioreHNlZ8Qg0Dv8n8=,tag:sU1ZMf3xh5QhNy3wPGuw2A==,type:str]
uptimeKuma:
    username: ENC[AES256_GCM,data:dgSfFHjrnw==,iv:2CfDxHRSzk67NLhCvlu5Dc7fi72YweOAmV7OW/dQVjM=,tag:1RvqtUoQfDZpWq1VWmyemw==,type:str]
    password: ENC[AES256_GCM,data:/h+OkulDS8x6GBbP1ColRsdWJDs=,iv:FTqp/bg4KAysE3UmsvN7RwK8NIqaAJmn7ggqCB/K+10=,tag:1uKoR7ZyXGa9WWYL5NX+Dg==,type:str]
    apiKey: ENC[AES256_GCM,data:wGolRdto3GQaGXRz/x1tnEWJpLCTQWonkEa9e/m70EOzLgABP7AFZacuq9k=,iv:qMSpeLrRxDwhBzzROJscDEnqFDfw8Z4EvfZXeDC5oxk=,tag:mAYCijd9TG8IqaURPFtdsg==,type:str]
podsync:
    username: ENC[AES256_GCM,data:8BqaPRe+t67j7XAP,iv:L0oVfBBH/k/2qx6I7b77iorwsLdhvQye+jAvKF4BFLI=,tag:F2hBoYQSIgjVoVJYqZIlHg==,type:str]
    password: ENC[AES256_GCM,data:ROoK1ozjfjMGPe/NTCYrk0VM0U3xMzAvdedGJKCCHX+ZYqD2LYQjgH8Lys0JJzHsUOnyvhLxtdTBKdSq,iv:4f5rJ1giqNj0bMKQwm+lDvMiW11HpiMf3JPX3qzeXb8=,tag:skR/AdomZNJL9eDTJ/f1Bw==,type:str]
    youtubeApiKey: ENC[AES256_GCM,data:sQV9se0T/W3SSf85BvpuEghj/q6pNdfUSChGq+g8gIoPF3WuRiB9,iv:t3YUZYdpRjFtf8N03Ly6w3BTZ9KcoeckiKrONWwjgSg=,tag:9opmu+81K+BeOgCfm5vsqQ==,type:str]
    vimeoApiKey: ENC[AES256_GCM,data:hRkO2lI/rmtNpgerwxLzIa5pSYVip8gOR6u6d0tmTC8=,iv:nNrehKLaIGSME24xWgIqhmIA85B4J22/LDUO2vGljow=,tag:BhcXcyrgKlbGkf9/RrRjkA==,type:str]
postgres:
    monitoring:
        password: ENC[AES256_GCM,data:SWciGi2U8VZProVjpQ==,iv:Sfhnlt/GdFyhRUi//Phz0pV8epeLbdw3hqHI5j6AipU=,tag:btKXmUJokTkgd0Mj8eubcw==,type:str]
sops:
    age:
        - recipient: age1nxsvvlxhutf7kr26ucc60r48lge779dducnknyr9pceej52nqgnqlvqe25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTFJLN3VhRy85bTZxeVRy
            em85UVk4cUpOM0E2cUxDQTJIQjRKZGpEdjNZClBWN1lZdWpXa2tsN3dkbkpZeXVF
            MnBERGVnMmRwMzgwNXdxYTBYLzZmQ1kKLS0tIEpGNnRWdjZuU3RUaVRVeGxyeG5w
            NUk5dXRIbmlQSTNJYVYwU3RtYzVWdGMKD/Rnrk6donTXNvuh2PTqecQoTsmIQASX
            5kWrGk3dsqeM8x5pywAAvCZ1NsAdS6ssjQIX/VuKRFh5ID8hCBWuCw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sxcheqlg4ztsu6ly3mfzmx7a2s7ht4znkez7q0g2rcmwr92tjfqqf29plr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMjB4Z2NBcXQrZlFjYTBR
            N0F5V2M1Y0ptdDkrY3A3a3ppbUNLM2lac0F3CnFyYnc4c1lub0s1eUlmRGtkWDVq
            YkFBYjhzQjZDWXUwUE5BR3FBNWI0OE0KLS0tIHVnK2JYOTN2a2ZGRzgxU1lnSE5W
            UEx5Y0MzdWY0bURpcDJmNDliaWRwRFkKQySkyXcI4lcvhNBngB5ilNAXR3c/MORL
            byXftpav9nAa3BIDIqMnOv4lh7wmy2nN7z9FdqoNAT7vehXK7+H/og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T13:23:22Z"
    mac: ENC[AES256_GCM,data:AKBuEPpE+sN7S+8edNh5sUFHeCT7LYU5fzuSTfqz7L/OBXvXYDiM52X42fevzb0Ls3oGonhdpcHA+FsAcKllECPGiZOycr1Yu+1k5/DXVZLbJ422CanvdKAIx7bLxYjPdqAaNghxt40JlofoBi8wv7W7cZDUTO8xY9+ekk5uvH0=,iv:XIluAdHn/kIKC28Rd2FTHuMCcPkLQ3l1idTCbtx7+2w=,tag://3BEtWX8ykz8GDJWi44nQ==,type:str]
    pgp:
        - created_at: "2025-10-24T18:57:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4ARsG/9MZa0AQ//X/m11WZdHu2oNhpxZwiSQpch+rlLVQkMJpExs0Rfn1Mm
            W8RG1+0z6JqS498KQZQQm+/Lgsf1OY1jC/k+Udq2v6H2vuuTVeZTW0aSLBIEXOSc
            lghV2+DbF3LYCBEDQd1P8xS1pQ75BI9qS3faOM8LvMvWscLkgxNhGMSxZxpKHZxh
            Zhkc2mINryyEtoLz5IeFnZDXQnXZ9Z51lNxherQahYTqDRsuAvFdSv24b9jfaMsr
            sh814/1d596XodywVaMny5+76/vGZQ5rZBPy8H/T6lDhOsyxGC/hOMJPCY/F6vLE
            Pqal3wFOh+LuSC+sqBK/19zs+e19KWG0sBIqay63EuTIa7OoRqtH6Vw0dGrJhTdl
            Ex8IG/uy2h8tGOP/N/mucINV+afbR3RFTgApE9omjiYuTLOhNMF0203EurxFEn5R
            VhLnAQcM9V7Q0P2pwXo7xbavOT4LE0BHBQ9QUEc1ZJJ/LsSt1+X648jkFH0pR4vT
            xwe4EsQ+Nr+y0gBEqwg/Q14ffnuHcvyuAB5MypEZi9ix01Zelm4DmvuViHghTKKJ
            V1g7SQT6MEQRrIJI4KFuWoPE74/4tTLK6RE/KvH0PfE4AAbSc53VstKGvJKBfTfr
            yc5Ds8yDPVuhV12yky0BYiJnwyzK0CghTFHhlfCT/RCLw81vpHPxxwzk1UzOrtnS
            UQG+kLt1I7ntiUcWktSORkSnIACoKIKlH2o8yBa7ZyjLn0UruSQmeWBR/A8XMUTr
            DvOKv8MwvGQhDhDDgbBsseLIa6DgYbRO1i5COPJdTZP3tQ==
            =3VM0
            -----END PGP MESSAGE-----
          fp: 6BD3724830BD941E9180C1A33A33FA4C82ED674F
    unencrypted_suffix: _unencrypted
    version: 3.11.0
